FROM denoland/deno:alpine AS base
WORKDIR /app

COPY package.json .

ARG OTODB_FRONTEND_DOMAIN
ENV OTODB_FRONTEND_DOMAIN=${OTODB_FRONTEND_DOMAIN}
ENV PUBLIC_BACKEND_URL_EXTERNAL=https://${OTODB_FRONTEND_DOMAIN}/
ENV PUBLIC_BACKEND_URL_INTERNAL=http://backend:8000/

RUN deno task install
RUN deno task prepare
EXPOSE 5173/tcp

COPY . .

ENTRYPOINT [ "sh", "-c", "exec env PROTOCOL_HEADER=x-forwarded-proto HOST_HEADER=x-forwarded-host PORT=5173 deno task dev --host 0.0.0.0" ]
