name: otodb

x-backend: &backend
  image: ghcr.io/otodb/otodb-backend:latest
  env_file:
    - .env
  environment:
    OTODB_DB_BACKEND: postgresql
    OTODB_DB_HOST: db
    OTODB_DB_PORT: "5432"
    OTODB_REDIS_URL: redis://redis:6379/0
  working_dir: /app
  depends_on:
    - db
    - redis
  restart: always

services:
  db:
    image: postgres:17.6
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${OTODB_DB_NAME}
      POSTGRES_USER: ${OTODB_DB_USER}
      POSTGRES_PASSWORD: ${OTODB_DB_PASSWORD}
    volumes:
      - postgres17_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: -c config_file=/etc/postgresql/postgresql.conf

  redis:
    image: redis:8-alpine
    restart: always

  backend:
    <<: *backend
    build: ./backend
    volumes:
      - /mnt/otodb-block/static:/app/static # Mount to specific location
      - ./cookies.txt:/app/cookies.txt:ro # Mount cookies for yt-dlp
      # - ./backend:/app  # For development purposes only
    stop_signal: SIGINT

  worker:
    <<: *backend
    command: ["python", "manage.py", "rqworker", "--with-scheduler", "--job-class", "django_tasks_rq.Job"]

  frontend:
    image: ghcr.io/otodb/otodb-frontend:latest
    build:
      context: ./frontend
      args:
        OTODB_HASH: ${OTODB_HASH:-}
    env_file:
      - .env
    restart: always

  caddy:
    image: caddy:2.9-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - /mnt/otodb-block/static:/srv/static
    depends_on:
      - backend
      - frontend

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  postgres17_data:
  caddy_data:
  caddy_config:
