"""Generate the PostgreSQL revision-capture triggers from the Django-free spec.

The trigger system replaces the Django ORM capture (dirtyfields + save/delete hooks +
request-cache). Capture lives in the DB, so any writer -- Django today, a future axum --
produces identical revision rows with no application-side capture code.

This module imports ONLY ``revision_spec`` (plain data) -- no Django -- so trigger
generation outlives the migration off Django. Generate with:

    python -m otodb.revision_codegen        > otodb/sql/revision_triggers.sql
    python -m otodb.revision_codegen --drop  # teardown / migration reverse_sql

A Django-based parity test keeps the spec honest against the models while both exist.
"""

from otodb.revision_spec import TABLES

_SHARED_SQL = """-- ===========================================================================
-- GENERATED by otodb/revision_codegen.py from otodb/revision_spec.py -- DO NOT EDIT.
-- Regenerate: python -m otodb.revision_codegen > otodb/sql/revision_triggers.sql
-- ===========================================================================

-- Content-type id for an app_label/model (STABLE: planner caches within a statement).
CREATE OR REPLACE FUNCTION otodb_ct(p_app text, p_model text)
RETURNS integer LANGUAGE sql STABLE AS $$
	SELECT id FROM django_content_type WHERE app_label = p_app AND model = p_model;
$$;

-- One Revision per transaction, created LAZILY on the first real change; its id is
-- parked in a txn-local setting so later changes in the same txn attach to it.
CREATE OR REPLACE FUNCTION otodb_current_revision()
RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
	rid bigint;
	uid text;
BEGIN
	rid := nullif(current_setting('otodb.rev_id', true), '')::bigint;
	IF rid IS NOT NULL THEN
		RETURN rid;
	END IF;
	uid := nullif(current_setting('otodb.user_id', true), '');
	INSERT INTO otodb_revision (user_id, "date", message)
	VALUES (
		uid::bigint,
		now(),
		coalesce(nullif(current_setting('otodb.message', true), ''), '')
	)
	RETURNING id INTO rid;
	PERFORM set_config('otodb.rev_id', rid::text, true);
	RETURN rid;
END;
$$;

-- Emit one RevisionChangeEntity row (skips NULL entity ids; idempotent).
CREATE OR REPLACE FUNCTION otodb_emit_entity(
	p_change bigint, p_entity_ct integer, p_entity_id bigint, p_route integer
)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
	IF p_entity_id IS NULL THEN
		RETURN;
	END IF;
	INSERT INTO otodb_revisionchangeentity (change_id, entity_type_id, entity_id, route)
	VALUES (p_change, p_entity_ct, p_entity_id, p_route)
	ON CONFLICT (change_id, entity_type_id, entity_id) DO NOTHING;
END;
$$;
"""


def _serialize(column, kind, alias):
	"""SQL on NEW/OLD reproducing Django value_to_string = str() for each field kind."""
	col = f'{alias}."{column}"'

	match kind:
		case 'str':
			return col
		case 'int' | 'fk':  # ints and str(pk) both stringify plainly
			return f'{col}::text'
		case 'bool':  # Python 'True'/'False', not PG 'true'/'false'
			return f"CASE WHEN {col} IS NULL THEN NULL WHEN {col} THEN 'True' ELSE 'False' END"
		case 'float':  # Python str() keeps the .0 that PG float8::text drops
			return (
				f'CASE WHEN {col} IS NULL THEN NULL'
				f" WHEN {col} = trunc({col}) AND abs({col}) < 1e16 THEN {col}::text || '.0'"
				f' ELSE {col}::text END'
			)
		case 'date':  # isoformat, DateStyle-proof, zero-padded
			return f"to_char({col}, 'YYYY-MM-DD')"
		case _:
			raise ValueError(f'unhandled field kind {kind!r} for column {column!r}')


def _table_sql(spec):
	table, app, model, pk = spec['table'], spec['app'], spec['model'], spec['pk']
	fn = f'otodb_{model}_capture'

	# One ct variable per distinct (app, model) referenced by entity routing.
	ct_var = {(app, model): 'own_ct'}
	decls = [
		'\trev bigint;',
		f'\ttid bigint := coalesce(NEW."{pk}", OLD."{pk}");',
		"\troute integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);",
		f"\town_ct integer := otodb_ct('{app}', '{model}');",
		'\tcid bigint;',
	]
	for _kind, e_app, e_model, _idcol in spec['entities']:
		key = (e_app, e_model)
		if key not in ct_var:
			var = f'ct_{e_model}'
			ct_var[key] = var
			decls.append(f"\t{var} integer := otodb_ct('{e_app}', '{e_model}');")

	def emit(alias):
		return '\n'.join(
			f'\t\tPERFORM otodb_emit_entity(cid, {ct_var[(e_app, e_model)]}, {alias}."{idcol}", route);'
			for _kind, e_app, e_model, idcol in spec['entities']
		)

	body = [
		"\tIF TG_OP = 'DELETE' THEN",
		'\t\tINSERT INTO otodb_revisionchange'
		' (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)',
		f'\t\tVALUES (otodb_current_revision(), own_ct, OLD."{pk}", NULL, NULL, true, false)',
		'\t\tON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING',
		'\t\tRETURNING id INTO cid;',
		'\t\tIF cid IS NOT NULL THEN',
		emit('OLD').replace('\t\t', '\t\t\t'),
		'\t\tEND IF;',
		'\t\tRETURN OLD;',
		'\tEND IF;',
		'',
	]

	for name, column, kind in spec['tracked']:
		changed = (
			f'TG_OP = \'INSERT\' OR NEW."{column}" IS DISTINCT FROM OLD."{column}"'
		)
		body += [
			f'\tIF {changed} THEN',
			'\t\tINSERT INTO otodb_revisionchange'
			' (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)',
			f"\t\tVALUES (otodb_current_revision(), own_ct, tid, '{name}', {_serialize(column, kind, 'NEW')}, false, false)",
			'\t\tON CONFLICT (rev_id, target_type_id, target_id, target_column)'
			' DO UPDATE SET target_value = EXCLUDED.target_value',
			'\t\tRETURNING id INTO cid;',
			emit('NEW'),
			'\tEND IF;',
		]
	body.append('\tRETURN NEW;')

	tracked_names = [name for name, _c, _k in spec['tracked']]
	return (
		f'-- {model}: tracked={tracked_names}\n'
		f'CREATE OR REPLACE FUNCTION {fn}() RETURNS trigger LANGUAGE plpgsql AS $$\n'
		f'DECLARE\n'
		+ '\n'.join(decls)
		+ '\nBEGIN\n'
		+ '\n'.join(body)
		+ '\nEND;\n$$;\n\n'
		f'DROP TRIGGER IF EXISTS zz_{fn} ON {table};\n'
		f'CREATE TRIGGER zz_{fn}\n'
		f'AFTER INSERT OR UPDATE OR DELETE ON {table}\n'
		f'FOR EACH ROW EXECUTE FUNCTION {fn}();\n'
	)


def generate_sql():
	"""Full install script: shared helpers + a capture trigger for every tracked table."""
	return '\n'.join([_SHARED_SQL, ''] + [_table_sql(spec) for spec in TABLES])


def generate_drop_sql():
	"""Teardown (migration reverse_sql): drop every per-table function CASCADE (removes
	its trigger) then the shared helpers."""
	lines = ['-- GENERATED by otodb/revision_codegen.py -- DO NOT EDIT.']
	for spec in TABLES:
		lines.append(
			f'DROP FUNCTION IF EXISTS otodb_{spec["model"]}_capture() CASCADE;'
		)
	lines += [
		'DROP FUNCTION IF EXISTS otodb_emit_entity(bigint, integer, bigint, integer);',
		'DROP FUNCTION IF EXISTS otodb_current_revision();',
		'DROP FUNCTION IF EXISTS otodb_ct(text, text);',
	]
	return '\n'.join(lines) + '\n'


if __name__ == '__main__':
	import sys

	sys.stdout.write(
		generate_drop_sql() if '--drop' in sys.argv[1:] else generate_sql()
	)
