# Generated by Django 6.0.4 on 2026-04-24 04:19

import dirtyfields.dirtyfields
import django.db.models.deletion
import django.db.models.manager
import tagulous.models.fields
import tagulous.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	replaces = [
		('otodb', '0001_initial'),
		('otodb', '0002_remove_historicaltagworkinstance_mean_score_and_more'),
		('otodb', '0003_pool_pending_items'),
		('otodb', '0004_alter_songrelation_relation_and_more'),
		('otodb', '0005_alter_historicaltagsong_options_and_more'),
		('otodb', '0006_post'),
		('otodb', '0007_alter_post_options_mediasongconnection_and_more'),
		('otodb', '0008_historicaltagwork_lang_historicalwikipage_lang_and_more'),
		('otodb', '0009_alter_historicaltagsong_options_and_more'),
		('otodb', '0010_alter_mediasongconnection_site_and_more'),
		('otodb', '0011_remove_historicaltagwork_lang_remove_tagwork_lang_and_more'),
		('otodb', '0012_tagsonglangpreference_tagworklangpreference'),
		('otodb', '0013_remove_historicaltagwork_wiki_page_and_more'),
		('otodb', '0014_alter_worksource_rejection_reason_and_more'),
		('otodb', '0015_alter_mediasongconnection_site'),
		('otodb', '0016_worksource_uploader_id'),
		('otodb', '0017_alter_mediasongconnection_unique_together_and_more'),
		('otodb', '0018_alter_mediasongconnection_unique_together_and_more'),
		('otodb', '0019_tagworkcreatorconnection_tagworksourceconnection'),
		(
			'otodb',
			'0020_alter_historicaltagworkinstance_instance_imported_from_source_and_more',
		),
		('otodb', '0021_alter_mediasongconnection_site'),
		('otodb', '0022_remove_worksource_rejection_reason_poolupstream_and_more'),
		('otodb', '0023_alter_tagwork_options_alter_worksource_options_and_more'),
		('otodb', '0024_worksource_info_payload'),
		('otodb', '0025_alter_tagsong_unique_together_alter_tagsong_slug_and_more'),
		('otodb', '0026_alter_worksource_uploader_id'),
		(
			'otodb',
			'0027_rename_song_used_as_source_historicaltagworkinstance_used_as_source_and_more',
		),
		('otodb', '0028_historicalmediasong_bpm_mixed_mediasong_bpm_mixed'),
		('otodb', '0029_historicaltagworkinstance_creator_roles_and_more'),
		('otodb', '0030_alter_worksource_options'),
		('otodb', '0031_historicaltagwork_deprecated_tagwork_deprecated'),
		('otodb', '0032_alter_worksource_media'),
		(
			'otodb',
			'0033_rename_tagworksourceconnection_tagworkmediaconnection_and_more',
		),
		('otodb', '0034_alter_tagwork_options'),
		('otodb', '0035_alter_tagwork_options'),
		('otodb', '0036_userpreferences_squashed_0039_alter_userpreferences_theme'),
		('otodb', '0040_alter_historicaltagsong_slug_and_more'),
		(
			'otodb',
			'0041_alter_historicalwikipage_tag_and_more_squashed_0043_historicalmediasong_tags',
		),
		('otodb', '0044_worksourceinfopayload'),
		('otodb', '0045_rename_info_payload_worksourceinfopayload_payload_and_more'),
		('otodb', '0046_remove_post_post_remove_post_post_rendered_and_more'),
		('otodb', '0047_alter_postcontent_unique_together'),
		(
			'otodb',
			'0048_tagworkparenthood_squashed_0048_alter_tagworkparenthood_unique_together_and_more',
		),
		('otodb', '0049_tagworkparenthood_tagwork_parenthood_nonreflexive'),
		('otodb', '0050_postcontent_modified'),
		('otodb', '0051_historicaltagwork_media_type_tagwork_media_type'),
		('otodb', '0052_historicaltagworkparenthood_primary_and_more'),
		(
			'otodb',
			'0053_alter_historicaltagworkconnection_site_and_more_squashed_0055_bulkrequest_done_alter_userrequest_bulk',
		),
		('otodb', '0056_remove_bulkrequest_done_bulkrequest_status'),
		('otodb', '0057_bulkrequest_processed_by_alter_userrequest_command_and_more'),
		('otodb', '0058_alter_historicalmediasong_bpm_alter_mediasong_bpm'),
		('otodb', '0059_historicaltagworkcreatorconnection_dead_and_more'),
		('otodb', '0060_post_category'),
		('otodb', '0061_normalize_tag_connections'),
		('otodb', '0062_rename_thumbnail_historicalmediawork__thumbnail_and_more'),
		('otodb', '0063_increase_slug_length'),
		('otodb', '0064_fix_truncated_slugs'),
		('otodb', '0065_delete_tagworkvote'),
		('otodb', '0066_alter_mediawork_options'),
		('otodb', '0067_historicalworksource_thumbnail_hash_and_more'),
		('otodb', '0068_alter_historicaltagworkmediaconnection_site_and_more'),
		('otodb', '0069_allow_null_published_date'),
		('otodb', '0070_allow_null_work_title'),
		('otodb', '0071_allow_null_and_blank_source_title'),
		(
			'otodb',
			'0072_remove_historicalmediasong_tags_history_and_more_squashed_0069_alter_revision_message_and_more',
		),
		('otodb', '0073_alter_revision_user'),
		('otodb', '0074_alter_revision_message'),
		('otodb', '0075_revisionchangeentity_route'),
		('otodb', '0076_revisionchange_restored_and_more'),
		('otodb', '0077_alter_mediawork_managers_alter_userpreferences_theme'),
		('otodb', '0078_alter_userpreferences_theme'),
		('otodb', '0079_alter_userpreferences_theme'),
		('otodb', '0080_alter_historicalworksource_platform_and_more'),
		('otodb', '0081_notification'),
		('otodb', '0082_alter_notification_target_subscription'),
		('otodb', '0083_remove_notification_message'),
		('otodb', '0084_remove_notification_entity_id_and_more'),
		('otodb', '0085_auto_20260125_1311'),
		('otodb', '0086_alter_tagsonglangpreference_unique_together_and_more'),
		('otodb', '0087_alter_revisionchangeentity_route_and_more'),
		('otodb', '0088_alter_worksource_platform'),
		('otodb', '0089_remove_notification_notification_union_and_more'),
		('otodb', '0090_alter_post_category_entitylink'),
		('otodb', '0091_post_edited_at_post_edited_by_commentmeta'),
		('otodb', '0092_auto_20260313_0901'),
		('otodb', '0093_alter_revisionchangeentity_route_and_more'),
		('otodb', '0094_alter_revisionchangeentity_route'),
		('otodb', '0095_remove_tagworkinstance_imported_from_source'),
		('otodb', '0096_remove_attach_tag_bulk_requests'),
		('otodb', '0097_alter_mediasongconnection_site'),
		('otodb', '0098_tag_display_names'),
		('otodb', '0099_alter_mediasong_tags_alter_mediawork_tags'),
		('otodb', '0100_alter_revisionchangeentity_route'),
		('otodb', '0101_alter_revisionchangeentity_route'),
		('otodb', '0102_post_closed_at'),
		('otodb', '0103_userpreference'),
		('otodb', '0104_notification_reason_and_order'),
		('otodb', '0105_moderationevent_mediawork_created_at_and_more'),
		('otodb', '0106_tagwork_add_new_general_category'),
		('otodb', '0107_notification_created_at'),
	]

	initial = True

	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('django_comments_xtd', '0008_auto_20200920_2037'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='MediaSong',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('title', models.CharField(max_length=1000)),
				('bpm', models.FloatField(null=True)),
				('variable_bpm', models.BooleanField(default=False)),
				('author', models.CharField(max_length=1000)),
			],
			options={
				'verbose_name': 'Song',
				'verbose_name_plural': 'Songs',
			},
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='BulkRequest',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'status',
					models.IntegerField(
						choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Unapproved')],
						default=0,
					),
				),
				(
					'processed_by',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name='processed_requests',
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'user',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='bulk_requests',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
		migrations.CreateModel(
			name='CommentMeta',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('edited_at', models.DateTimeField(blank=True, null=True)),
				(
					'comment',
					models.OneToOneField(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='meta',
						to='django_comments_xtd.xtdcomment',
					),
				),
				(
					'edited_by',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='edited_comments',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
		migrations.CreateModel(
			name='MediaSongConnection',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'site',
					models.IntegerField(
						choices=[
							(0, 'VGMdb'),
							(1, 'VocaDB'),
							(2, 'Discogs'),
							(3, 'MusicBrainz'),
							(4, 'Rate Your Music'),
							(5, 'dojin-music.info'),
							(6, 'TouhouDB'),
							(20, 'RemyWiki'),
							(21, 'Silent Blue'),
							(22, 'Zenius -I- vanisher.com'),
							(30, 'NND Medley Wiki'),
							(40, 'The Mod Archive'),
						]
					),
				),
				('content_id', models.CharField(max_length=1000)),
				(
					'song',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.mediasong',
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='MediaWork',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('title', models.CharField(blank=True, max_length=1000, null=True)),
				('description', models.TextField(blank=True, null=True)),
				(
					'rating',
					models.IntegerField(
						choices=[(0, 'General'), (1, 'Sensitive'), (2, 'Explicit')],
						default=0,
					),
				),
				(
					'status',
					models.IntegerField(
						choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Unapproved')],
						default=1,
					),
				),
				('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
				(
					'_thumbnail',
					models.CharField(
						blank=True,
						help_text='Deprecated: Use thumbnail_source instead',
						max_length=200,
						null=True,
					),
				),
				(
					'moved_to',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.mediawork',
					),
				),
			],
			options={
				'verbose_name': 'Work',
				'verbose_name_plural': 'Works',
				'ordering': ['-id'],
			},
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='Pool',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('name', models.CharField(max_length=255)),
				('description', models.TextField(blank=True, null=True)),
				(
					'author',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				'verbose_name': 'List',
				'verbose_name_plural': 'Lists',
			},
		),
		migrations.CreateModel(
			name='PoolItem',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'order',
					models.PositiveIntegerField(
						db_index=True, editable=False, verbose_name='order'
					),
				),
				('description', models.TextField(blank=True, null=True)),
				(
					'pool',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.pool'
					),
				),
				(
					'work',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.mediawork',
					),
				),
			],
			options={
				'verbose_name': 'List Entry',
				'verbose_name_plural': 'List Entries',
				'ordering': ('order',),
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='PoolUpstream',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('upstream', models.URLField()),
				(
					'pool',
					models.OneToOneField(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.pool'
					),
				),
			],
		),
		migrations.CreateModel(
			name='Post',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('title', models.CharField(max_length=1000)),
				(
					'category',
					models.IntegerField(
						choices=[
							(0, 'Announcement'),
							(1, 'Feature Request'),
							(2, 'Bug Report'),
							(3, 'Gardening'),
							(4, 'General'),
						]
					),
				),
				('closed_at', models.DateTimeField(blank=True, null=True)),
				('edited_at', models.DateTimeField(blank=True, null=True)),
				(
					'added_by',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'edited_by',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='edited_posts',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				'verbose_name': 'Post',
				'verbose_name_plural': 'Posts',
			},
		),
		migrations.CreateModel(
			name='EntityLink',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('entity_id', models.PositiveBigIntegerField()),
				(
					'entity_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
				(
					'post',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.post'
					),
				),
			],
		),
		migrations.CreateModel(
			name='PostContent',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('page', models.TextField()),
				(
					'lang',
					models.IntegerField(
						choices=[
							(0, 'N/A'),
							(1, 'en'),
							(2, 'ja'),
							(3, 'zh-cn'),
							(4, 'ko'),
						]
					),
				),
				('modified', models.DateTimeField(auto_now=True)),
				(
					'post',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.post'
					),
				),
			],
		),
		migrations.CreateModel(
			name='ProfileConnection',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'site',
					models.IntegerField(
						choices=[
							(0, 'Website'),
							(1, 'Niconico'),
							(2, 'YouTube'),
							(3, 'Bilibili'),
							(4, 'Twitter'),
							(5, 'Bluesky'),
							(6, 'Soundcloud'),
						]
					),
				),
				('content_id', models.CharField(max_length=1000)),
				(
					'profile',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
		migrations.CreateModel(
			name='Revision',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('date', models.DateTimeField(auto_now_add=True)),
				('message', models.TextField(default='')),
				(
					'user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.PROTECT,
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
		migrations.CreateModel(
			name='Notification',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
				('dismissed', models.BooleanField(default=False)),
				(
					'reason',
					models.IntegerField(
						choices=[(0, 'Reply'), (1, 'Mention'), (2, 'Thread Linked')],
						default=0,
					),
				),
				(
					'comment',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						to='django_comments_xtd.xtdcomment',
					),
				),
				(
					'target',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='notifs',
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'post',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.post',
					),
				),
				(
					'revision',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.revision',
					),
				),
			],
			options={
				'ordering': ['dismissed', '-id'],
			},
		),
		migrations.CreateModel(
			name='RevisionChange',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('target_id', models.PositiveBigIntegerField()),
				('deleted', models.BooleanField(default=False)),
				('restored', models.BooleanField(default=False)),
				('target_column', models.CharField(max_length=100, null=True)),
				('target_value', models.TextField(null=True)),
				(
					'rev',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.revision'
					),
				),
				(
					'target_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
			],
		),
		migrations.CreateModel(
			name='RevisionChangeEntity',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('entity_id', models.PositiveBigIntegerField()),
				(
					'route',
					models.IntegerField(
						choices=[
							(0, 'Unknown'),
							(1, 'Tag Work Alias'),
							(2, 'Tag Work Alias Control'),
							(3, 'Tag Work Delete'),
							(4, 'Tag Work Update'),
							(7, 'Tag Work Edit Wiki'),
							(8, 'Tag Work Edit Connections'),
							(20, 'Song Tag Update'),
							(21, 'Song Tag Set Tags'),
							(22, 'Song Tag Alias'),
							(23, 'Song Tag Alias Control'),
							(24, 'Song Tag Delete'),
							(30, 'Song Relation Control'),
							(40, 'Media Work Delete'),
							(41, 'Media Work Set Tags'),
							(45, 'Media Work Update'),
							(46, 'Media Work Merge'),
							(47, 'Media Work Create'),
							(50, 'Work Relation Control'),
							(60, 'Work Source Create'),
							(61, 'Work Source Unbind'),
							(62, 'Work Source Set Origin'),
							(63, 'Work Source Refresh'),
							(64, 'Work Source Assign'),
							(65, 'Work Source Reject'),
							(66, 'Work Source Update'),
							(100, 'Rollback'),
						],
						default=0,
					),
				),
				(
					'change',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.revisionchange',
					),
				),
				(
					'entity_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
			],
		),
		migrations.CreateModel(
			name='SongRelation',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'relation',
					models.IntegerField(
						choices=[
							(0, 'Remix'),
							(1, 'Remaster'),
							(2, 'Medley'),
							(3, 'Sequel'),
						]
					),
				),
				(
					'A',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='relation_A',
						to='otodb.mediasong',
					),
				),
				(
					'B',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='relation_B',
						to='otodb.mediasong',
					),
				),
			],
			options={
				'verbose_name': 'Song relation',
				'verbose_name_plural': 'Song relations',
			},
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='Subscription',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('entity_id', models.PositiveBigIntegerField()),
				(
					'entity_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
				(
					'subscriber',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
		migrations.CreateModel(
			name='TagSong',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('name', models.CharField(max_length=255, unique=True)),
				(
					'slug',
					models.SlugField(allow_unicode=True, max_length=255, unique=True),
				),
				(
					'count',
					models.IntegerField(
						default=0,
						help_text='Internal counter of how many times this tag is in use',
					),
				),
				(
					'protected',
					models.BooleanField(
						default=False,
						help_text='Will not be deleted when the count reaches 0',
					),
				),
				(
					'category',
					models.IntegerField(
						choices=[
							(0, 'General'),
							(1, 'Genre'),
							(2, 'Author'),
							(3, 'Meta'),
						],
						default=0,
					),
				),
				(
					'aliased_to',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name='aliases',
						to='otodb.tagsong',
					),
				),
				(
					'parent',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='children',
						to='otodb.tagsong',
					),
				),
			],
			bases=(
				tagulous.models.models.BaseTagModel,
				dirtyfields.dirtyfields.DirtyFieldsMixin,
				models.Model,
			),
		),
		migrations.CreateModel(
			name='TagSongInstance',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'song',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.mediasong',
					),
				),
				(
					'song_tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.tagsong'
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.AddField(
			model_name='mediasong',
			name='tags',
			field=tagulous.models.fields.TagField(
				_set_tag_meta=True,
				case_sensitive=False,
				force_lowercase=False,
				help_text='Enter a comma-separated tag string',
				protect_all=True,
				related_name='songs',
				through='otodb.TagSongInstance',
				to='otodb.tagsong',
			),
		),
		migrations.CreateModel(
			name='TagSongLangPreference',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'lang',
					models.IntegerField(
						choices=[
							(0, 'N/A'),
							(1, 'en'),
							(2, 'ja'),
							(3, 'zh-cn'),
							(4, 'ko'),
						],
						default=0,
					),
				),
				(
					'tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.tagsong'
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='TagWork',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('name', models.CharField(max_length=255, unique=True)),
				(
					'slug',
					models.SlugField(allow_unicode=True, max_length=255, unique=True),
				),
				(
					'count',
					models.IntegerField(
						default=0,
						help_text='Internal counter of how many times this tag is in use',
					),
				),
				(
					'protected',
					models.BooleanField(
						default=False,
						help_text='Will not be deleted when the count reaches 0',
					),
				),
				('deprecated', models.BooleanField(default=False)),
				(
					'category',
					models.IntegerField(
						choices=[
							(0, 'Uncategorized'),
							(1, 'Event'),
							(2, 'Song'),
							(3, 'Source'),
							(4, 'Creator'),
							(5, 'Meta'),
							(6, 'Media'),
							(7, 'General'),
						],
						default=0,
					),
				),
				(
					'media_type',
					models.IntegerField(
						blank=True, help_text='Media type bitmask', null=True
					),
				),
				(
					'aliased_to',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name='aliases',
						to='otodb.tagwork',
					),
				),
			],
			options={
				'ordering': [
					models.Case(
						models.When(category=1, then=models.Value(0)),
						models.When(category=4, then=models.Value(10)),
						models.When(category=6, then=models.Value(11)),
						models.When(category=3, then=models.Value(20)),
						models.When(category=2, then=models.Value(30)),
						models.When(category=5, then=models.Value(1000)),
						models.When(category=0, then=models.Value(9999)),
						default=models.Value(999),
						output_field=models.IntegerField(),
					),
					'name',
				],
			},
			bases=(
				tagulous.models.models.BaseTagModel,
				dirtyfields.dirtyfields.DirtyFieldsMixin,
				models.Model,
			),
		),
		migrations.AddField(
			model_name='mediasong',
			name='work_tag',
			field=models.OneToOneField(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.CreateModel(
			name='TagWorkConnection',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'site',
					models.IntegerField(
						choices=[
							(1, 'otomad.wiki'),
							(2, 'Otomad Wiki 2'),
							(20, 'Niconico Encyclopedia'),
							(21, 'Pixiv Dictionary'),
							(22, 'Wikipedia'),
							(23, 'Namu Wiki'),
							(24, 'Know Your Meme'),
						]
					),
				),
				('content_id', models.CharField(max_length=1000)),
				(
					'tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='TagWorkCreatorConnection',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'site',
					models.IntegerField(
						choices=[
							(0, 'Website'),
							(1, 'Niconico'),
							(2, 'YouTube'),
							(3, 'Bilibili'),
							(4, 'Twitter'),
							(5, 'Bluesky'),
							(6, 'Soundcloud'),
						]
					),
				),
				('content_id', models.CharField(max_length=1000)),
				('dead', models.BooleanField(default=False)),
				(
					'tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='TagWorkInstance',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('used_as_source', models.BooleanField(default=False)),
				(
					'creator_roles',
					models.IntegerField(
						blank=True, help_text='Creator role bitmask', null=True
					),
				),
				(
					'work',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.mediawork',
					),
				),
				(
					'work_tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.AddField(
			model_name='mediawork',
			name='tags',
			field=tagulous.models.fields.TagField(
				_set_tag_meta=True,
				case_sensitive=False,
				force_lowercase=False,
				help_text='Enter a comma-separated tag string',
				protect_all=True,
				related_name='works',
				through='otodb.TagWorkInstance',
				to='otodb.tagwork',
			),
		),
		migrations.CreateModel(
			name='TagWorkLangPreference',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'lang',
					models.IntegerField(
						choices=[
							(0, 'N/A'),
							(1, 'en'),
							(2, 'ja'),
							(3, 'zh-cn'),
							(4, 'ko'),
						],
						default=0,
					),
				),
				(
					'tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='TagWorkMediaConnection',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'site',
					models.IntegerField(
						choices=[
							(1, 'AniKore'),
							(2, 'Bangumi'),
							(3, 'AniDB'),
							(4, 'MyAnimeList'),
							(5, 'AniList'),
							(6, 'Kitsu'),
							(7, 'Anime-Planet'),
							(20, 'IMDb'),
							(21, 'Letterboxd'),
							(40, 'vndb'),
							(41, 'ErogameScape'),
							(50, 'VGMdb'),
						]
					),
				),
				('content_id', models.CharField(max_length=1000)),
				(
					'tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='TagWorkParenthood',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('primary', models.BooleanField(default=False)),
				(
					'parent',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='parenthood',
						to='otodb.tagwork',
					),
				),
				(
					'tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='childhood',
						to='otodb.tagwork',
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='UserPreference',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'setting',
					models.IntegerField(choices=[(1, 'Language'), (2, 'Theme')]),
				),
				('value', models.IntegerField()),
				(
					'user',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='preferences',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
		migrations.CreateModel(
			name='UserRequest',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'command',
					models.IntegerField(
						choices=[
							(1, 'Tagwork Alias'),
							(2, 'Tagwork Unalias'),
							(3, 'Tagwork Deprecate'),
							(4, 'Tagwork Undeprecate'),
							(5, 'Tagwork Parent'),
							(6, 'Tagwork Unparent'),
						]
					),
				),
				('A_id', models.PositiveBigIntegerField()),
				('B_id', models.PositiveBigIntegerField()),
				(
					'A_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='requests_A',
						to='contenttypes.contenttype',
					),
				),
				(
					'B_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='requests_B',
						to='contenttypes.contenttype',
					),
				),
				(
					'bulk',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='requests',
						to='otodb.bulkrequest',
					),
				),
			],
		),
		migrations.CreateModel(
			name='WikiPage',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('page', models.TextField()),
				(
					'lang',
					models.IntegerField(
						choices=[
							(0, 'N/A'),
							(1, 'en'),
							(2, 'ja'),
							(3, 'zh-cn'),
							(4, 'ko'),
						],
						default=0,
					),
				),
				(
					'tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
					),
				),
			],
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='WorkRelation',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'relation',
					models.IntegerField(
						choices=[
							(0, 'Sequel'),
							(1, 'Respect'),
							(2, 'Collab Part'),
							(3, 'Sample'),
						]
					),
				),
				(
					'A',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='relation_A',
						to='otodb.mediawork',
					),
				),
				(
					'B',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='relation_B',
						to='otodb.mediawork',
					),
				),
			],
			options={
				'verbose_name': 'Work relation',
				'verbose_name_plural': 'Work relations',
			},
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.CreateModel(
			name='WorkSource',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'platform',
					models.IntegerField(
						choices=[
							(1, 'YouTube'),
							(2, 'Niconico'),
							(3, 'Bilibili'),
							(4, 'SoundCloud'),
							(5, 'Twitter'),
							(6, 'AcFun'),
						]
					),
				),
				('source_id', models.CharField(max_length=1000, null=True)),
				('url', models.URLField()),
				('published_date', models.DateField(blank=True, null=True)),
				(
					'work_origin',
					models.IntegerField(
						choices=[(0, 'Author'), (1, 'Reupload')], default=0
					),
				),
				(
					'work_status',
					models.IntegerField(
						choices=[(0, 'Available'), (1, 'Down')], default=0
					),
				),
				('work_width', models.PositiveIntegerField(blank=True, null=True)),
				('work_height', models.PositiveIntegerField(blank=True, null=True)),
				('work_duration', models.PositiveIntegerField(blank=True, null=True)),
				('title', models.CharField(blank=True, max_length=1000, null=True)),
				('description', models.TextField(blank=True, null=True)),
				('thumbnail_url', models.URLField(null=True)),
				(
					'thumbnail_mime',
					models.IntegerField(
						blank=True,
						choices=[
							(1, 'image/jpeg'),
							(2, 'image/png'),
							(3, 'image/webp'),
						],
						null=True,
					),
				),
				(
					'thumbnail_hash',
					models.CharField(blank=True, max_length=64, null=True),
				),
				('uploader_id', models.CharField(max_length=1000, null=True)),
				('is_pending', models.BooleanField(default=False)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				(
					'added_by',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'media',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.mediawork',
					),
				),
			],
			options={
				'verbose_name': 'Media Source',
				'verbose_name_plural': 'Media Sources',
				'ordering': ['work_status', 'work_origin', 'published_date'],
			},
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
			managers=[
				('active_objects', django.db.models.manager.Manager()),
			],
		),
		migrations.AddField(
			model_name='pool',
			name='pending_items',
			field=models.ManyToManyField(to='otodb.worksource'),
		),
		migrations.CreateModel(
			name='ModerationEvent',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'event_type',
					models.IntegerField(
						choices=[
							(0, 'Flag'),
							(1, 'Appeal'),
							(2, 'Disapproval'),
							(3, 'Approval'),
							(4, 'Mod Action'),
						]
					),
				),
				('reason', models.CharField(blank=True, default='', max_length=1000)),
				(
					'status',
					models.IntegerField(
						blank=True,
						choices=[(0, 'Pending'), (1, 'Succeeded'), (2, 'Rejected')],
						null=True,
					),
				),
				('date', models.DateTimeField(auto_now_add=True, db_index=True)),
				(
					'by',
					models.ForeignKey(
						on_delete=django.db.models.deletion.RESTRICT,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'work',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='moderation_events',
						to='otodb.mediawork',
					),
				),
				(
					'source',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='moderation_events',
						to='otodb.worksource',
					),
				),
			],
			options={
				'ordering': ['-date'],
			},
		),
		migrations.AddField(
			model_name='mediawork',
			name='thumbnail_source',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				to='otodb.worksource',
			),
		),
		migrations.CreateModel(
			name='WorkSourceInfoPayload',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('payload', models.JSONField()),
				(
					'source',
					models.OneToOneField(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='info_payload',
						to='otodb.worksource',
					),
				),
			],
		),
		migrations.AddConstraint(
			model_name='bulkrequest',
			constraint=models.CheckConstraint(
				condition=models.Q(
					models.Q(
						('status', 0), ('processed_by__isnull', False), _connector='OR'
					),
					models.Q(
						('processed_by__isnull', True),
						models.Q(('status', 0), _negated=True),
						_connector='OR',
					),
				),
				name='request_processed_by_notnull_iff_not_pending',
				violation_error_message='processed_by null <=> status is pending',
			),
		),
		migrations.AlterUniqueTogether(
			name='mediasongconnection',
			unique_together={('song', 'site', 'content_id')},
		),
		migrations.AddConstraint(
			model_name='entitylink',
			constraint=models.UniqueConstraint(
				fields=('entity_type', 'entity_id', 'post'),
				name='entitylink_unique_post',
			),
		),
		migrations.AlterUniqueTogether(
			name='postcontent',
			unique_together={('post', 'lang')},
		),
		migrations.AlterUniqueTogether(
			name='profileconnection',
			unique_together={('profile', 'site', 'content_id')},
		),
		migrations.AddConstraint(
			model_name='notification',
			constraint=models.CheckConstraint(
				condition=models.Q(
					models.Q(
						('comment__isnull', True),
						('post__isnull', True),
						('revision__isnull', False),
					),
					models.Q(
						('comment__isnull', False),
						('post__isnull', True),
						('revision__isnull', True),
					),
					models.Q(
						('comment__isnull', True),
						('post__isnull', False),
						('revision__isnull', True),
					),
					_connector='OR',
				),
				name='notification_union',
			),
		),
		migrations.AddIndex(
			model_name='revisionchange',
			index=models.Index(
				fields=['target_type', 'target_id'], name='revisionchange_target_idx'
			),
		),
		migrations.AddConstraint(
			model_name='revisionchange',
			constraint=models.CheckConstraint(
				condition=models.Q(
					('deleted', True), ('restored', True), _negated=True
				),
				name='revisionchange_cannot_be_both_delete_and_restore',
			),
		),
		migrations.AddConstraint(
			model_name='revisionchange',
			constraint=models.UniqueConstraint(
				condition=models.Q(('deleted', True)),
				fields=('target_type', 'target_id'),
				name='revisionchange_model_can_only_be_deleted_once',
			),
		),
		migrations.AddConstraint(
			model_name='revisionchange',
			constraint=models.UniqueConstraint(
				condition=models.Q(('restored', True)),
				fields=('target_type', 'target_id'),
				name='revisionchange_model_can_only_be_restored_once',
			),
		),
		migrations.AlterUniqueTogether(
			name='revisionchange',
			unique_together={('rev', 'target_type', 'target_id', 'target_column')},
		),
		migrations.AlterUniqueTogether(
			name='revisionchangeentity',
			unique_together={('change', 'entity_type', 'entity_id')},
		),
		migrations.AddConstraint(
			model_name='songrelation',
			constraint=models.UniqueConstraint(
				fields=('A', 'B'), name='unique_relation_between_songs'
			),
		),
		migrations.AddConstraint(
			model_name='songrelation',
			constraint=models.CheckConstraint(
				condition=models.Q(('A', models.F('B')), _negated=True),
				name='song_relation_nonreflexive',
				violation_error_message='A must be different from B',
			),
		),
		migrations.AddConstraint(
			model_name='subscription',
			constraint=models.UniqueConstraint(
				fields=('subscriber', 'entity_type', 'entity_id'),
				name='unique_subscription',
			),
		),
		migrations.AddConstraint(
			model_name='tagsong',
			constraint=models.CheckConstraint(
				condition=models.Q(('parent_id', models.F('id')), _negated=True),
				name='tagsong_parenthood_nonreflexive',
				violation_error_message='tag cannot be own parent',
			),
		),
		migrations.AlterUniqueTogether(
			name='tagsonginstance',
			unique_together={('song', 'song_tag')},
		),
		migrations.AlterUniqueTogether(
			name='tagsonglangpreference',
			unique_together={('tag', 'lang')},
		),
		migrations.AddConstraint(
			model_name='mediasong',
			constraint=models.CheckConstraint(
				condition=models.Q(('bpm__gt', 0)),
				name='song_bpm_positive',
				violation_error_message='BPM must be positive',
			),
		),
		migrations.AlterUniqueTogether(
			name='tagworkconnection',
			unique_together={('tag', 'site', 'content_id')},
		),
		migrations.AlterUniqueTogether(
			name='tagworkcreatorconnection',
			unique_together={('tag', 'site', 'content_id')},
		),
		migrations.AlterUniqueTogether(
			name='tagworkinstance',
			unique_together={('work', 'work_tag')},
		),
		migrations.AlterUniqueTogether(
			name='tagworklangpreference',
			unique_together={('tag', 'lang')},
		),
		migrations.AlterUniqueTogether(
			name='tagworkmediaconnection',
			unique_together={('tag', 'site', 'content_id')},
		),
		migrations.AddConstraint(
			model_name='tagworkparenthood',
			constraint=models.CheckConstraint(
				condition=models.Q(('tag', models.F('parent')), _negated=True),
				name='tagwork_parenthood_nonreflexive',
				violation_error_message='tag cannot be own parent',
			),
		),
		migrations.AddConstraint(
			model_name='tagworkparenthood',
			constraint=models.UniqueConstraint(
				condition=models.Q(('primary', True)),
				fields=('tag',),
				name='tagwork_parenthood_at_most_one_primary',
			),
		),
		migrations.AlterUniqueTogether(
			name='tagworkparenthood',
			unique_together={('tag', 'parent')},
		),
		migrations.AddConstraint(
			model_name='userpreference',
			constraint=models.UniqueConstraint(
				fields=('user', 'setting'),
				name='userpreference_single_value_for_setting',
			),
		),
		migrations.AlterUniqueTogether(
			name='userrequest',
			unique_together={('bulk', 'command', 'A_type', 'A_id', 'B_type', 'B_id')},
		),
		migrations.AlterUniqueTogether(
			name='wikipage',
			unique_together={('tag', 'lang')},
		),
		migrations.AddConstraint(
			model_name='workrelation',
			constraint=models.UniqueConstraint(
				fields=('A', 'B'), name='unique_relation_between_works'
			),
		),
		migrations.AddConstraint(
			model_name='workrelation',
			constraint=models.CheckConstraint(
				condition=models.Q(('A', models.F('B')), _negated=True),
				name='work_relation_nonreflexive',
				violation_error_message='A must be different from B',
			),
		),
		migrations.AddIndex(
			model_name='moderationevent',
			index=models.Index(
				fields=['event_type', 'status'], name='otodb_moder_event_t_e72254_idx'
			),
		),
		migrations.AddIndex(
			model_name='moderationevent',
			index=models.Index(
				fields=['work', 'event_type'], name='otodb_moder_work_id_e763b1_idx'
			),
		),
		migrations.AddConstraint(
			model_name='moderationevent',
			constraint=models.UniqueConstraint(
				condition=models.Q(('event_type__in', [0, 1]), ('status', 0)),
				fields=('work',),
				name='unique_pending_moderation_per_work',
				violation_error_message='This work already has a pending flag or appeal',
			),
		),
		migrations.AddConstraint(
			model_name='moderationevent',
			constraint=models.UniqueConstraint(
				condition=models.Q(('event_type', 2)),
				fields=('work', 'by'),
				name='unique_disapproval_per_work_per_user',
			),
		),
	]
