# Generated by Django 5.1.6 on 2025-03-13 16:53

import django.db.models.deletion
import markdownfield.models
import simple_history.models
import tagulous.models.fields
import tagulous.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', markdownfield.models.MarkdownField(rendered_field='page_rendered')),
                ('page_rendered', markdownfield.models.RenderedMarkdownField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalWikiPage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('page', markdownfield.models.MarkdownField(rendered_field='page_rendered')),
                ('page_rendered', markdownfield.models.RenderedMarkdownField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical wiki page',
                'verbose_name_plural': 'historical wiki pages',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MediaWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(0, 'General'), (1, 'Sensitive'), (2, 'Explicit')], default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('moved_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='otodb.mediawork')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMediaWork',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(choices=[(0, 'General'), (1, 'Sensitive'), (2, 'Explicit')], default=0)),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moved_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otodb.mediawork')),
            ],
            options={
                'verbose_name': 'historical Work',
                'verbose_name_plural': 'historical Works',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
            },
        ),
        migrations.CreateModel(
            name='PoolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('description', models.TextField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otodb.pool')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otodb.mediawork')),
            ],
            options={
                'verbose_name': 'List Entry',
                'verbose_name_plural': 'List Entries',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TagSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('category', models.IntegerField(choices=[(0, 'General'), (1, 'Genre'), (2, 'Language'), (3, 'Author'), (4, 'Meta')], default=0)),
                ('aliased_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='otodb.tagsong')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otodb.tagsong')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'permissions': [('manage_tags', 'Can manage tags')],
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTagSong',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('category', models.IntegerField(choices=[(0, 'General'), (1, 'Genre'), (2, 'Language'), (3, 'Author'), (4, 'Meta')], default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('aliased_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otodb.tagsong')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otodb.tagsong')),
            ],
            options={
                'verbose_name': 'historical Tag',
                'verbose_name_plural': 'historical Tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TagWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('category', models.IntegerField(choices=[(0, 'General'), (1, 'Language'), (2, 'Song'), (3, 'Source'), (4, 'Creator'), (5, 'Meta')], default=0)),
                ('aliased_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='otodb.tagwork')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='otodb.tagwork')),
                ('wiki_page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otodb.wikipage')),
            ],
            options={
                'verbose_name': 'Work Tag',
                'verbose_name_plural': 'Work Tags',
                'permissions': [('manage_tags', 'Can manage tags')],
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.CreateModel(
            name='MediaSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('bpm', models.FloatField()),
                ('author', models.CharField(max_length=1000)),
                ('tags', tagulous.models.fields.TagField(_set_tag_meta=True, case_sensitive=False, force_lowercase=True, help_text='Enter a comma-separated tag string', protect_all=True, related_name='song_tags', to='otodb.tagsong')),
                ('work_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork')),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTagWorkInstance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mean_score', models.FloatField(default=0.0)),
                ('song_used_as_source', models.BooleanField(default=False)),
                ('instance_imported_from_source', models.BooleanField(default=False)),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='otodb.historicalmediawork')),
                ('work', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otodb.mediawork')),
                ('work_tag', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otodb.tagwork')),
            ],
            options={
                'verbose_name': 'HistoricalTagWorkInstance',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMediaSong',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('bpm', models.FloatField()),
                ('author', models.CharField(max_length=1000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_tag', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otodb.tagwork')),
            ],
            options={
                'verbose_name': 'historical Song',
                'verbose_name_plural': 'historical Songs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TagWorkInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_score', models.FloatField(default=0.0)),
                ('song_used_as_source', models.BooleanField(default=False)),
                ('instance_imported_from_source', models.BooleanField(default=False)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otodb.mediawork')),
                ('work_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork')),
            ],
        ),
        migrations.AddField(
            model_name='mediawork',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, case_sensitive=False, force_lowercase=True, help_text='Enter a comma-separated tag string', protect_all=True, related_name='works', through='otodb.TagWorkInstance', to='otodb.tagwork'),
        ),
        migrations.CreateModel(
            name='TagWorkVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('tag_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otodb.tagworkinstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTagWork',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
                ('category', models.IntegerField(choices=[(0, 'General'), (1, 'Language'), (2, 'Song'), (3, 'Source'), (4, 'Creator'), (5, 'Meta')], default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('aliased_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otodb.tagwork')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otodb.tagwork')),
                ('wiki_page', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='otodb.wikipage')),
            ],
            options={
                'verbose_name': 'historical Work Tag',
                'verbose_name_plural': 'historical Work Tags',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(choices=[(1, 'Sequel'), (2, 'Respect'), (3, 'Collab Part'), (4, 'Sample')])),
                ('A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_A', to='otodb.mediawork')),
                ('B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_B', to='otodb.mediawork')),
            ],
            options={
                'verbose_name': 'Work relation',
                'verbose_name_plural': 'Work relations',
            },
        ),
        migrations.CreateModel(
            name='WorkSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(1, 'YouTube'), (2, 'Niconico'), (3, 'Bilibili'), (4, 'SoundCloud')])),
                ('source_id', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('published_date', models.DateField()),
                ('work_origin', models.IntegerField(choices=[(0, 'Author'), (1, 'Reupload')], default=0)),
                ('work_status', models.IntegerField(choices=[(0, 'Available'), (1, 'Down')], default=0)),
                ('work_width', models.PositiveIntegerField(blank=True, null=True)),
                ('work_height', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(null=True)),
                ('rejection_reason', models.CharField(max_length=1000, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='otodb.mediawork')),
            ],
            options={
                'verbose_name': 'Media Source',
                'verbose_name_plural': 'Media Sources',
            },
        ),
        migrations.CreateModel(
            name='SongRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(choices=[(1, 'Remix'), (2, 'Remaster'), (3, 'Medley'), (4, 'Sequel')])),
                ('A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_A', to='otodb.mediasong')),
                ('B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_B', to='otodb.mediasong')),
            ],
            options={
                'verbose_name': 'Song relation',
                'verbose_name_plural': 'Song relations',
                'constraints': [models.UniqueConstraint(fields=('A', 'B'), name='unique_relation_between_songs'), models.CheckConstraint(condition=models.Q(('A', models.F('B')), _negated=True), name='song_relation_nonreflexive', violation_error_message='A must be different from B')],
            },
        ),
        migrations.AddConstraint(
            model_name='mediasong',
            constraint=models.CheckConstraint(condition=models.Q(('bpm__gt', 0)), name='song_bpm_positive', violation_error_message='BPM must be positive'),
        ),
        migrations.AlterUniqueTogether(
            name='tagworkinstance',
            unique_together={('work', 'work_tag')},
        ),
        migrations.AddConstraint(
            model_name='workrelation',
            constraint=models.UniqueConstraint(fields=('A', 'B'), name='unique_relation_between_works'),
        ),
        migrations.AddConstraint(
            model_name='workrelation',
            constraint=models.CheckConstraint(condition=models.Q(('A', models.F('B')), _negated=True), name='work_relation_nonreflexive', violation_error_message='A must be different from B'),
        ),
    ]
