# Generated by Django 5.1.6 on 2025-03-01 18:24

import django.db.models.deletion
import tagulous.models.fields
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worksource',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediawork',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, case_sensitive=False, force_lowercase=True, help_text='Enter a comma-separated tag string', protect_all=True, related_name='works', through='otodb.TagWorkInstance', to='otodb.tagwork'),
        ),
        migrations.AlterField(
            model_name='tagwork',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='otodb.tagwork'),
        ),
    ]
