# Generated by Django 5.1.6 on 2025-03-19 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otodb", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltagworkinstance",
            name="mean_score",
        ),
        migrations.RemoveField(
            model_name="tagworkinstance",
            name="mean_score",
        ),
        migrations.AlterUniqueTogether(
            name="tagworkvote",
            unique_together={("user", "tag_instance")},
        ),
        migrations.AddConstraint(
            model_name="tagworkvote",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", -1), ("score__lte", 1)),
                name="tagwork_vote_in_pn_1",
                violation_error_message="TagWork vote score must be in [-1, 1]",
            ),
        ),
    ]
