# Generated by Django 5.1.6 on 2025-03-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otodb", "0002_remove_historicaltagworkinstance_mean_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="pending_items",
            field=models.ManyToManyField(to="otodb.worksource"),
        ),
    ]
