# Generated by Django 5.1.6 on 2025-03-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0002_worksource_added_by_alter_mediawork_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksource',
            name='rejected',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
