# Generated by Django 5.1.6 on 2025-03-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0003_worksource_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksource',
            name='rejected',
        ),
        migrations.AddField(
            model_name='worksource',
            name='rejection_reason',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
