# Generated by Django 5.2.1 on 2025-05-24 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0006_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.CreateModel(
            name='MediaSongConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.IntegerField(choices=[(0, 'VGMdb'), (1, 'VocaDB'), (2, 'Discogs'), (3, 'Rate Your Music'), (4, 'RemyWiki'), (5, 'Zenius -I- vanisher.com')])),
                ('content_id', models.CharField(max_length=1000)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otodb.mediasong')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.IntegerField(choices=[(0, 'Niconico'), (1, 'YouTube'), (2, 'Bilibili'), (3, 'X'), (4, 'Bluesky')])),
                ('content_id', models.CharField(max_length=1000)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagWorkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.IntegerField(choices=[(1, 'otomad.wiki'), (2, 'Otomad Wiki 2'), (3, 'Niconico Encyclopedia'), (4, 'KnowYourMeme'), (5, 'Wikipedia'), (6, 'Namu Wiki'), (7, 'AniKore'), (8, 'Bangumi'), (9, 'AniDB'), (10, 'MyAnimeList'), (0, 'Website')])),
                ('content_id', models.CharField(max_length=1000)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork')),
            ],
        ),
    ]
