# Generated by Django 5.2.1 on 2025-05-25 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otodb", "0012_tagsonglangpreference_tagworklangpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltagwork",
            name="wiki_page",
        ),
        migrations.RemoveField(
            model_name="tagwork",
            name="wiki_page",
        ),
        migrations.AddField(
            model_name="historicalwikipage",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="otodb.tagwork",
            ),
        ),
        migrations.AddField(
            model_name="wikipage",
            name="tag",
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to="otodb.tagwork",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="mediasongconnection",
            unique_together={("song", "site")},
        ),
        migrations.AlterUniqueTogether(
            name="profileconnection",
            unique_together={("profile", "site")},
        ),
        migrations.AlterUniqueTogether(
            name="tagworkconnection",
            unique_together={("tag", "site")},
        ),
        migrations.AlterUniqueTogether(
            name="wikipage",
            unique_together={("tag", "lang")},
        ),
    ]
