# Generated by Django 5.2.1 on 2025-05-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0013_remove_historicaltagwork_wiki_page_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='worksource',
			name='rejection_reason',
			field=models.CharField(blank=True, max_length=1000, null=True),
		),
		migrations.AlterUniqueTogether(
			name='tagworklangpreference',
			unique_together={('tag', 'lang')},
		),
	]
