# Generated by Django 5.2.1 on 2025-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		(
			'otodb',
			'0020_alter_historicaltagworkinstance_instance_imported_from_source_and_more',
		),
	]

	operations = [
		migrations.AlterField(
			model_name='mediasongconnection',
			name='site',
			field=models.IntegerField(
				choices=[
					(0, 'VGMdb'),
					(1, 'VocaDB'),
					(2, 'Discogs'),
					(3, 'MusicBrainz'),
					(4, 'Rate Your Music'),
					(5, 'dojin-music.info'),
					(20, 'RemyWiki'),
					(21, 'Silent Blue'),
					(22, 'Zenius -I- vanisher.com'),
					(30, 'NND Medley Wiki'),
				]
			),
		),
	]
