# Generated by Django 5.2.1 on 2025-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otodb", "0023_alter_tagwork_options_alter_worksource_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksource",
            name="info_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
