# Generated by Django 5.2.1 on 2025-07-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0025_alter_tagsong_unique_together_alter_tagsong_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksource',
            name='uploader_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
