# Generated by Django 5.2.1 on 2025-07-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0026_alter_worksource_uploader_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltagworkinstance',
            old_name='song_used_as_source',
            new_name='used_as_source',
        ),
        migrations.RenameField(
            model_name='tagworkinstance',
            old_name='song_used_as_source',
            new_name='used_as_source',
        ),
    ]
