# Generated by Django 5.2.1 on 2025-07-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0027_rename_song_used_as_source_historicaltagworkinstance_used_as_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmediasong',
            name='bpm_mixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediasong',
            name='bpm_mixed',
            field=models.BooleanField(default=False),
        ),
    ]
