# Generated by Django 5.2.1 on 2025-07-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0027_rename_song_used_as_source_historicaltagworkinstance_used_as_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltagworkinstance',
            name='creator_roles',
            field=models.IntegerField(blank=True, help_text='Bitfield of creator roles for this work', null=True),
        ),
        migrations.AddField(
            model_name='tagworkinstance',
            name='creator_roles',
            field=models.IntegerField(blank=True, help_text='Bitfield of creator roles for this work', null=True),
        ),
    ]
