# Generated by Django 5.2.1 on 2025-07-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0028_historicalmediasong_bpm_mixed_mediasong_bpm_mixed'),
	]

	operations = [
		migrations.AddField(
			model_name='historicaltagworkinstance',
			name='creator_roles',
			field=models.IntegerField(
				blank=True, help_text='Creator role bitmask', null=True
			),
		),
		migrations.AddField(
			model_name='tagworkinstance',
			name='creator_roles',
			field=models.IntegerField(
				blank=True, help_text='Creator role bitmask', null=True
			),
		),
	]
