# Generated by Django 5.2.1 on 2025-07-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0028_historicaltagworkinstance_creator_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltagworkinstance',
            name='creator_roles',
            field=models.IntegerField(blank=True, help_text='Creator role bitmask', null=True),
        ),
        migrations.AlterField(
            model_name='tagworkinstance',
            name='creator_roles',
            field=models.IntegerField(blank=True, help_text='Creator role bitmask', null=True),
        ),
    ]
