# Generated by Django 5.2.1 on 2025-07-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0030_alter_worksource_options'),
	]

	operations = [
		migrations.AddField(
			model_name='historicaltagwork',
			name='deprecated',
			field=models.BooleanField(default=False),
		),
		migrations.AddField(
			model_name='tagwork',
			name='deprecated',
			field=models.BooleanField(default=False),
		),
	]
