# Generated by Django 5.2.1 on 2025-08-17 09:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0040_alter_historicaltagsong_slug_and_more'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AlterField(
			model_name='historicalwikipage',
			name='tag',
			field=simple_history.models.HistoricForeignKey(
				blank=True,
				db_constraint=False,
				null=True,
				on_delete=django.db.models.deletion.DO_NOTHING,
				related_name='+',
				to='otodb.tagwork',
			),
		),
		migrations.AlterField(
			model_name='mediasongconnection',
			name='song',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.mediasong'
			),
		),
		migrations.AlterField(
			model_name='tagworkconnection',
			name='tag',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.AlterField(
			model_name='tagworkcreatorconnection',
			name='tag',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.AlterField(
			model_name='tagworkmediaconnection',
			name='tag',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.AlterField(
			model_name='wikipage',
			name='tag',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.CreateModel(
			name='HistoricalMediaSongConnection',
			fields=[
				(
					'id',
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name='ID'
					),
				),
				(
					'site',
					models.IntegerField(
						choices=[
							(0, 'VGMdb'),
							(1, 'VocaDB'),
							(2, 'Discogs'),
							(3, 'MusicBrainz'),
							(4, 'Rate Your Music'),
							(5, 'dojin-music.info'),
							(20, 'RemyWiki'),
							(21, 'Silent Blue'),
							(22, 'Zenius -I- vanisher.com'),
							(30, 'NND Medley Wiki'),
						]
					),
				),
				('content_id', models.CharField(max_length=1000)),
				('history_id', models.AutoField(primary_key=True, serialize=False)),
				('history_date', models.DateTimeField(db_index=True)),
				('history_change_reason', models.CharField(max_length=100, null=True)),
				(
					'history_type',
					models.CharField(
						choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
						max_length=1,
					),
				),
				(
					'history_user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='+',
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'song',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.mediasong',
					),
				),
			],
			options={
				'verbose_name': 'historical media song connection',
				'verbose_name_plural': 'historical media song connections',
				'ordering': ('-history_date', '-history_id'),
				'get_latest_by': ('history_date', 'history_id'),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.CreateModel(
			name='HistoricalTagWorkConnection',
			fields=[
				(
					'id',
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name='ID'
					),
				),
				(
					'site',
					models.IntegerField(
						choices=[
							(1, 'otomad.wiki'),
							(2, 'Otomad Wiki 2'),
							(20, 'Niconico Encyclopedia'),
							(21, 'Pixiv Dictionary'),
							(22, 'Wikipedia'),
							(23, 'Namu Wiki'),
							(24, 'Know Your Meme'),
						]
					),
				),
				('content_id', models.CharField(max_length=1000)),
				('history_id', models.AutoField(primary_key=True, serialize=False)),
				('history_date', models.DateTimeField(db_index=True)),
				('history_change_reason', models.CharField(max_length=100, null=True)),
				(
					'history_type',
					models.CharField(
						choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
						max_length=1,
					),
				),
				(
					'history_user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='+',
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'tag',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.tagwork',
					),
				),
			],
			options={
				'verbose_name': 'historical tag work connection',
				'verbose_name_plural': 'historical tag work connections',
				'ordering': ('-history_date', '-history_id'),
				'get_latest_by': ('history_date', 'history_id'),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.CreateModel(
			name='HistoricalTagWorkCreatorConnection',
			fields=[
				(
					'id',
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name='ID'
					),
				),
				(
					'site',
					models.IntegerField(
						choices=[
							(0, 'Website'),
							(1, 'Niconico'),
							(2, 'YouTube'),
							(3, 'Bilibili'),
							(4, 'Twitter'),
							(5, 'Bluesky'),
						]
					),
				),
				('content_id', models.CharField(max_length=1000)),
				('history_id', models.AutoField(primary_key=True, serialize=False)),
				('history_date', models.DateTimeField(db_index=True)),
				('history_change_reason', models.CharField(max_length=100, null=True)),
				(
					'history_type',
					models.CharField(
						choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
						max_length=1,
					),
				),
				(
					'history_user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='+',
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'tag',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.tagwork',
					),
				),
			],
			options={
				'verbose_name': 'historical tag work creator connection',
				'verbose_name_plural': 'historical tag work creator connections',
				'ordering': ('-history_date', '-history_id'),
				'get_latest_by': ('history_date', 'history_id'),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.CreateModel(
			name='HistoricalTagWorkMediaConnection',
			fields=[
				(
					'id',
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name='ID'
					),
				),
				(
					'site',
					models.IntegerField(
						choices=[
							(1, 'AniKore'),
							(2, 'Bangumi'),
							(3, 'AniDB'),
							(4, 'MyAnimeList'),
							(5, 'AniList'),
							(6, 'Kitsu'),
							(7, 'Anime-Planet'),
							(20, 'IMDb'),
							(21, 'Letterboxd'),
							(40, 'vndb'),
							(41, 'ErogameScape'),
						]
					),
				),
				('content_id', models.CharField(max_length=1000)),
				('history_id', models.AutoField(primary_key=True, serialize=False)),
				('history_date', models.DateTimeField(db_index=True)),
				('history_change_reason', models.CharField(max_length=100, null=True)),
				(
					'history_type',
					models.CharField(
						choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
						max_length=1,
					),
				),
				(
					'history_user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='+',
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'tag',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.tagwork',
					),
				),
			],
			options={
				'verbose_name': 'historical tag work media connection',
				'verbose_name_plural': 'historical tag work media connections',
				'ordering': ('-history_date', '-history_id'),
				'get_latest_by': ('history_date', 'history_id'),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.AlterField(
			model_name='songrelation',
			name='A',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='relation_A',
				to='otodb.mediasong',
			),
		),
		migrations.AlterField(
			model_name='songrelation',
			name='B',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='relation_B',
				to='otodb.mediasong',
			),
		),
		migrations.AlterField(
			model_name='tagworklangpreference',
			name='tag',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.AlterField(
			model_name='workrelation',
			name='A',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='relation_A',
				to='otodb.mediawork',
			),
		),
		migrations.AlterField(
			model_name='workrelation',
			name='B',
			field=simple_history.models.HistoricForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='relation_B',
				to='otodb.mediawork',
			),
		),
		migrations.AlterField(
			model_name='worksource',
			name='media',
			field=simple_history.models.HistoricForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to='otodb.mediawork',
			),
		),
		migrations.CreateModel(
			name='HistoricalSongRelation',
			fields=[
				(
					'id',
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name='ID'
					),
				),
				(
					'relation',
					models.IntegerField(
						choices=[
							(0, 'Remix'),
							(1, 'Remaster'),
							(2, 'Medley'),
							(3, 'Sequel'),
						]
					),
				),
				('history_id', models.AutoField(primary_key=True, serialize=False)),
				('history_date', models.DateTimeField(db_index=True)),
				('history_change_reason', models.CharField(max_length=100, null=True)),
				(
					'history_type',
					models.CharField(
						choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
						max_length=1,
					),
				),
				(
					'A',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.mediasong',
					),
				),
				(
					'B',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.mediasong',
					),
				),
				(
					'history_user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='+',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				'verbose_name': 'historical Song relation',
				'verbose_name_plural': 'historical Song relations',
				'ordering': ('-history_date', '-history_id'),
				'get_latest_by': ('history_date', 'history_id'),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.CreateModel(
			name='HistoricalTagWorkLangPreference',
			fields=[
				(
					'id',
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name='ID'
					),
				),
				(
					'lang',
					models.IntegerField(
						choices=[
							(0, 'N/A'),
							(1, 'en'),
							(2, 'ja'),
							(3, 'zh-cn'),
							(4, 'ko'),
						],
						default=0,
					),
				),
				('history_id', models.AutoField(primary_key=True, serialize=False)),
				('history_date', models.DateTimeField(db_index=True)),
				('history_change_reason', models.CharField(max_length=100, null=True)),
				(
					'history_type',
					models.CharField(
						choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
						max_length=1,
					),
				),
				(
					'history_user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='+',
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'tag',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.tagwork',
					),
				),
			],
			options={
				'verbose_name': 'historical tag work lang preference',
				'verbose_name_plural': 'historical tag work lang preferences',
				'ordering': ('-history_date', '-history_id'),
				'get_latest_by': ('history_date', 'history_id'),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.CreateModel(
			name='HistoricalWorkRelation',
			fields=[
				(
					'id',
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name='ID'
					),
				),
				(
					'relation',
					models.IntegerField(
						choices=[
							(0, 'Sequel'),
							(1, 'Respect'),
							(2, 'Collab Part'),
							(3, 'Sample'),
						]
					),
				),
				('history_id', models.AutoField(primary_key=True, serialize=False)),
				('history_date', models.DateTimeField(db_index=True)),
				('history_change_reason', models.CharField(max_length=100, null=True)),
				(
					'history_type',
					models.CharField(
						choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
						max_length=1,
					),
				),
				(
					'A',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.mediawork',
					),
				),
				(
					'B',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.mediawork',
					),
				),
				(
					'history_user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='+',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				'verbose_name': 'historical Work relation',
				'verbose_name_plural': 'historical Work relations',
				'ordering': ('-history_date', '-history_id'),
				'get_latest_by': ('history_date', 'history_id'),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.CreateModel(
			name='HistoricalWorkSource',
			fields=[
				(
					'id',
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name='ID'
					),
				),
				(
					'platform',
					models.IntegerField(
						choices=[
							(1, 'YouTube'),
							(2, 'Niconico'),
							(3, 'Bilibili'),
							(4, 'SoundCloud'),
						]
					),
				),
				('source_id', models.CharField(max_length=1000)),
				('url', models.URLField()),
				('published_date', models.DateField()),
				(
					'work_origin',
					models.IntegerField(
						choices=[(0, 'Author'), (1, 'Reupload')], default=0
					),
				),
				(
					'work_status',
					models.IntegerField(
						choices=[(0, 'Available'), (1, 'Down')], default=0
					),
				),
				('work_width', models.PositiveIntegerField(blank=True, null=True)),
				('work_height', models.PositiveIntegerField(blank=True, null=True)),
				('work_duration', models.PositiveIntegerField(blank=True, null=True)),
				('title', models.CharField(max_length=1000)),
				('description', models.TextField(blank=True, null=True)),
				('thumbnail', models.URLField(null=True)),
				('uploader_id', models.CharField(max_length=1000, null=True)),
				('info_payload', models.JSONField(blank=True, null=True)),
				('history_id', models.AutoField(primary_key=True, serialize=False)),
				('history_date', models.DateTimeField(db_index=True)),
				('history_change_reason', models.CharField(max_length=100, null=True)),
				(
					'history_type',
					models.CharField(
						choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
						max_length=1,
					),
				),
				(
					'added_by',
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'history_user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='+',
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'media',
					simple_history.models.HistoricForeignKey(
						blank=True,
						db_constraint=False,
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.mediawork',
					),
				),
			],
			options={
				'verbose_name': 'historical Media Source',
				'verbose_name_plural': 'historical Media Sources',
				'ordering': ('-history_date', '-history_id'),
				'get_latest_by': ('history_date', 'history_id'),
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
		migrations.CreateModel(
			name='HistoricalMediaSong_tags',
			fields=[
				(
					'id',
					models.BigIntegerField(
						auto_created=True, blank=True, db_index=True, verbose_name='ID'
					),
				),
				('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
				(
					'history',
					models.ForeignKey(
						db_constraint=False,
						on_delete=django.db.models.deletion.DO_NOTHING,
						to='otodb.historicalmediasong',
					),
				),
				(
					'mediasong',
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						db_tablespace='',
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.mediasong',
					),
				),
				(
					'tagsong',
					models.ForeignKey(
						blank=True,
						db_constraint=False,
						db_tablespace='',
						null=True,
						on_delete=django.db.models.deletion.DO_NOTHING,
						related_name='+',
						to='otodb.tagsong',
					),
				),
			],
			options={
				'verbose_name': 'HistoricalMediaSong_tags',
			},
			bases=(simple_history.models.HistoricalChanges, models.Model),
		),
	]
