# Generated by Django 5.2.1 on 2025-08-20 17:01

import django.db.models.deletion
from django.db import migrations, models

def move_column_data(apps, schema_editor):
    OriginalModel = apps.get_model('otodb', 'TagWork')
    NewModel = apps.get_model('otodb', 'TagWorkParenthood')

    for t in OriginalModel.objects.filter(parent__isnull=False).all():
        NewModel.objects.create(
            tag=t,
            parent=t.parent
        )


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0045_rename_info_payload_worksourceinfopayload_payload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagWorkParenthood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childhood', to='otodb.tagwork')),
            ],
        ),
        migrations.RunPython(move_column_data),
    ]
