# Generated by Django 5.2.1 on 2025-08-20 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0046_tagworkparenthood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltagwork',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tagwork',
            name='parent',
        ),
        migrations.AlterField(
            model_name='tagworkparenthood',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parenthood', to='otodb.tagwork'),
        ),
    ]
