# Generated by Django 5.2.1 on 2025-08-21 02:38

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0046_remove_post_post_remove_post_post_rendered_and_more'),
	]

	operations = [
		migrations.AlterUniqueTogether(
			name='postcontent',
			unique_together={('post', 'lang')},
		),
	]
