# Generated by Django 5.2.1 on 2025-08-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("otodb", "0049_tagworkparenthood_tagwork_parenthood_nonreflexive"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcontent",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
