# Generated by Django 5.2.1 on 2025-08-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0050_postcontent_modified'),
	]

	operations = [
		migrations.AddField(
			model_name='historicaltagwork',
			name='media_type',
			field=models.IntegerField(
				blank=True, help_text='Media type bitmask', null=True
			),
		),
		migrations.AddField(
			model_name='tagwork',
			name='media_type',
			field=models.IntegerField(
				blank=True, help_text='Media type bitmask', null=True
			),
		),
	]
