# Generated by Django 5.2.1 on 2025-08-31 06:54

import django.db.models.deletion
import otodb.models.request
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('otodb', '0053_alter_historicaltagworkconnection_site_and_more'), ('otodb', '0054_alter_bulkrequest_user'), ('otodb', '0055_bulkrequest_done_alter_userrequest_bulk')]

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('otodb', '0052_historicaltagworkparenthood_primary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltagworkconnection',
            name='site',
            field=models.IntegerField(choices=[(0, 'Website'), (1, 'otomad.wiki'), (2, 'Otomad Wiki 2'), (20, 'Niconico Encyclopedia'), (21, 'Pixiv Dictionary'), (22, 'Wikipedia'), (23, 'Namu Wiki'), (24, 'Know Your Meme')]),
        ),
        migrations.AlterField(
            model_name='tagworkconnection',
            name='site',
            field=models.IntegerField(choices=[(0, 'Website'), (1, 'otomad.wiki'), (2, 'Otomad Wiki 2'), (20, 'Niconico Encyclopedia'), (21, 'Pixiv Dictionary'), (22, 'Wikipedia'), (23, 'Namu Wiki'), (24, 'Know Your Meme')]),
        ),
        migrations.CreateModel(
            name='BulkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_requests', to=settings.AUTH_USER_MODEL)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.IntegerField(verbose_name=otodb.models.request.BulkRequest)),
                ('A_id', models.PositiveBigIntegerField()),
                ('B_id', models.PositiveBigIntegerField()),
                ('A_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_A', to='contenttypes.contenttype')),
                ('B_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_B', to='contenttypes.contenttype')),
                ('bulk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='otodb.bulkrequest')),
            ],
            options={
                'unique_together': {('bulk', 'command', 'A_type', 'A_id', 'B_type', 'B_id')},
            },
        ),
    ]
