# Generated by Django 5.2.1 on 2025-09-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0057_bulkrequest_processed_by_alter_userrequest_command_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='historicalmediasong',
			name='bpm',
			field=models.FloatField(null=True),
		),
		migrations.AlterField(
			model_name='mediasong',
			name='bpm',
			field=models.FloatField(null=True),
		),
	]
