# Generated by Django 5.2.1 on 2025-09-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0058_rename_thumbnail_historicalmediawork__thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediawork',
            name='thumbnail_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otodb.worksource'),
        ),
    ]
