# Generated by Django 5.2.1 on 2025-09-27 22:51

from django.db import migrations
import re
def re_to_parser(regex):
    def matcher(link):
        m = regex.fullmatch(link)
        if m:
            return m.group(1)
    return matcher
def make_alt_value_parser(*parsers):
    def match(link):
        for v, parser in parsers:
            parse = parser(link)
            if parse:
                return (v, parse)
    return match
profile_connection_parser = make_alt_value_parser(
	(0, re_to_parser(re.compile(r'(https?://.+)'))),
	(1, re_to_parser(re.compile(r'https?:\/\/www\.nicovideo\.jp\/user\/(\d+)\/?'))),
	(2, re_to_parser(re.compile(r'https?:\/\/www\.youtube\.com\/([^/?#]+(?:\/[^/?#]+)*)\/?'))),
	(3, re_to_parser(re.compile(r'https?:\/\/space\.bilibili\.com\/(\d+)\/?'))),
	(4, re_to_parser(re.compile(r'https?:\/\/(?:twitter|x)\.com\/((?:[A-Za-z0-9_]{1,15})|(?:i\/user\/\d+))\/?'))),
	(5, re_to_parser(re.compile(r'https?:\/\/bsky\.app\/profile\/(.+?)(?:\/*)')))
	(6, re_to_parser(re.compile(r'https?:\/\/soundcloud\.com\/(.+?)(?:\/*)')))
)

def fix_tag_connections(apps, schema_editor):
    WikiPage = apps.get_model('otodb', 'WikiPage')
    TagWorkConnection = apps.get_model('otodb', 'TagWorkConnection')
    TagWorkCreatorConnection = apps.get_model('otodb', 'TagWorkCreatorConnection')
    
    for con in TagWorkConnection.objects.filter(site=0):
        tag = con.tag
        if tag.category == 4:
            parse = profile_connection_parser(con.content_id)
            if parse:
                TagWorkCreatorConnection.objects.create(tag=tag, dead=False, site=parse[0], content_id=parse[1])
        else:
            try:
                page = tag.wikipage_set.get(lang=1)
                page.page += f'\n\n[{con.content_id}]({con.content_id})'
            except WikiPage.DoesNotExist:
                WikiPage.objects.create(lang=1, tag=tag, page=f'[{con.content_id}]({con.content_id})')

        con.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0060_post_category'),
    ]

    operations = [
    ]
    operations = [
        migrations.RunPython(fix_tag_connections),
    ]
