# Generated by Django 5.2.7 on 2025-10-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0062_rename_thumbnail_historicalmediawork__thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmediasongconnection',
            name='site',
            field=models.IntegerField(choices=[(0, 'VGMdb'), (1, 'VocaDB'), (2, 'Discogs'), (3, 'MusicBrainz'), (4, 'Rate Your Music'), (5, 'dojin-music.info'), (20, 'RemyWiki'), (21, 'Silent Blue'), (22, 'Zenius -I- vanisher.com'), (30, 'NND Medley Wiki'), (40, 'The Mod Archive')]),
        ),
        migrations.AlterField(
            model_name='historicalmediawork',
            name='_thumbnail',
            field=models.CharField(blank=True, help_text='Deprecated: Use thumbnail_source instead', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltagsong',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltagwork',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltagworkconnection',
            name='site',
            field=models.IntegerField(choices=[(1, 'otomad.wiki'), (2, 'Otomad Wiki 2'), (20, 'Niconico Encyclopedia'), (21, 'Pixiv Dictionary'), (22, 'Wikipedia'), (23, 'Namu Wiki'), (24, 'Know Your Meme')]),
        ),
        migrations.AlterField(
            model_name='historicaltagworkcreatorconnection',
            name='site',
            field=models.IntegerField(choices=[(0, 'Website'), (1, 'Niconico'), (2, 'YouTube'), (3, 'Bilibili'), (4, 'Twitter'), (5, 'Bluesky'), (6, 'Soundcloud')]),
        ),
        migrations.AlterField(
            model_name='mediasongconnection',
            name='site',
            field=models.IntegerField(choices=[(0, 'VGMdb'), (1, 'VocaDB'), (2, 'Discogs'), (3, 'MusicBrainz'), (4, 'Rate Your Music'), (5, 'dojin-music.info'), (20, 'RemyWiki'), (21, 'Silent Blue'), (22, 'Zenius -I- vanisher.com'), (30, 'NND Medley Wiki'), (40, 'The Mod Archive')]),
        ),
        migrations.AlterField(
            model_name='mediawork',
            name='_thumbnail',
            field=models.CharField(blank=True, help_text='Deprecated: Use thumbnail_source instead', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profileconnection',
            name='site',
            field=models.IntegerField(choices=[(0, 'Website'), (1, 'Niconico'), (2, 'YouTube'), (3, 'Bilibili'), (4, 'Twitter'), (5, 'Bluesky'), (6, 'Soundcloud')]),
        ),
        migrations.AlterField(
            model_name='tagsong',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tagwork',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tagworkconnection',
            name='site',
            field=models.IntegerField(choices=[(1, 'otomad.wiki'), (2, 'Otomad Wiki 2'), (20, 'Niconico Encyclopedia'), (21, 'Pixiv Dictionary'), (22, 'Wikipedia'), (23, 'Namu Wiki'), (24, 'Know Your Meme')]),
        ),
        migrations.AlterField(
            model_name='tagworkcreatorconnection',
            name='site',
            field=models.IntegerField(choices=[(0, 'Website'), (1, 'Niconico'), (2, 'YouTube'), (3, 'Bilibili'), (4, 'Twitter'), (5, 'Bluesky'), (6, 'Soundcloud')]),
        ),
    ]
