# Generated by Django 5.2.7 on 2025-10-26 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0064_fix_truncated_slugs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagWorkVote',
        ),
    ]
