# Generated by Django 5.2.7 on 2025-10-29 04:58

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0065_delete_tagworkvote'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='mediawork',
			options={
				'ordering': ['-id'],
				'verbose_name': 'Work',
				'verbose_name_plural': 'Works',
			},
		),
	]
