# Generated by Django 5.2.7 on 2025-10-28 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0066_remove_historicalmediasong_tags_history_and_more'),
	]

	operations = [
		migrations.RemoveField(
			model_name='revisionchange',
			name='entity_id',
		),
		migrations.RemoveField(
			model_name='revisionchange',
			name='entity_type',
		),
		migrations.AlterField(
			model_name='revisionchange',
			name='target_column',
			field=models.CharField(max_length=100, null=True),
		),
		migrations.AlterField(
			model_name='revisionchange',
			name='target_value',
			field=models.TextField(null=True),
		),
		migrations.CreateModel(
			name='RevisionChangeEntity',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('entity_id', models.PositiveBigIntegerField()),
				(
					'change',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.revisionchange',
					),
				),
				(
					'entity_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='entity_revision_changes',
						to='contenttypes.contenttype',
					),
				),
			],
			options={
				'unique_together': {('change', 'entity_type', 'entity_id')},
			},
		),
	]
