# Generated by Django 5.2.7 on 2025-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0067_historicalworksource_thumbnail_hash_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='historicaltagworkmediaconnection',
			name='site',
			field=models.IntegerField(
				choices=[
					(1, 'AniKore'),
					(2, 'Bangumi'),
					(3, 'AniDB'),
					(4, 'MyAnimeList'),
					(5, 'AniList'),
					(6, 'Kitsu'),
					(7, 'Anime-Planet'),
					(20, 'IMDb'),
					(21, 'Letterboxd'),
					(40, 'vndb'),
					(41, 'ErogameScape'),
					(50, 'VGMdb'),
				]
			),
		),
		migrations.AlterField(
			model_name='tagworkmediaconnection',
			name='site',
			field=models.IntegerField(
				choices=[
					(1, 'AniKore'),
					(2, 'Bangumi'),
					(3, 'AniDB'),
					(4, 'MyAnimeList'),
					(5, 'AniList'),
					(6, 'Kitsu'),
					(7, 'Anime-Planet'),
					(20, 'IMDb'),
					(21, 'Letterboxd'),
					(40, 'vndb'),
					(41, 'ErogameScape'),
					(50, 'VGMdb'),
				]
			),
		),
	]
