# Generated by Django 5.2.7 on 2025-10-28 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0067_remove_revisionchange_entity_id_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='revision',
			name='message',
			field=models.TextField(null=True),
		),
		migrations.AlterField(
			model_name='revisionchange',
			name='target_type',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				to='contenttypes.contenttype',
			),
		),
		migrations.AlterField(
			model_name='revisionchangeentity',
			name='entity_type',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				to='contenttypes.contenttype',
			),
		),
	]
