# Generated by Django 5.2.7 on 2025-11-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0068_alter_historicaltagworkmediaconnection_site_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='historicalworksource',
			name='published_date',
			field=models.DateField(blank=True, null=True),
		),
		migrations.AlterField(
			model_name='worksource',
			name='published_date',
			field=models.DateField(blank=True, null=True),
		),
	]
