# Generated by Django 5.2.7 on 2025-10-28 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		(
			'otodb',
			'0067_remove_historicalmediasong_tags_history_and_more_squashed_0068_alter_revision_message_and_more',
		),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AlterField(
			model_name='revision',
			name='user',
			field=models.ForeignKey(
				null=True,
				on_delete=django.db.models.deletion.PROTECT,
				to=settings.AUTH_USER_MODEL,
			),
		),
	]
