# Generated by Django 5.2.7 on 2025-11-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0069_allow_null_published_date'),
	]

	operations = [
		migrations.AlterField(
			model_name='historicalmediawork',
			name='title',
			field=models.CharField(blank=True, max_length=1000, null=True),
		),
		migrations.AlterField(
			model_name='mediawork',
			name='title',
			field=models.CharField(blank=True, max_length=1000, null=True),
		),
	]
