# Generated by Django 5.2.7 on 2025-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0070_allow_null_work_title'),
	]

	operations = [
		migrations.AlterField(
			model_name='historicalworksource',
			name='title',
			field=models.CharField(blank=True, max_length=1000, null=True),
		),
		migrations.AlterField(
			model_name='worksource',
			name='title',
			field=models.CharField(blank=True, max_length=1000, null=True),
		),
	]
