# Generated by Django 5.2.7 on 2025-10-28 11:21

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def initial_revision(apps, schema_editor):
	Revision = apps.get_model('otodb', 'Revision')
	RevisionChange = apps.get_model('otodb', 'RevisionChange')
	RevisionChangeEntity = apps.get_model('otodb', 'RevisionChangeEntity')
	ContentType = apps.get_model('contenttypes', 'ContentType')
	from django.apps import apps
	old_models_with_history = [
		'MediaSong',
		'MediaSongConnection',
		'MediaWork',
		'SongRelation',
		'TagSong',
		'TagWork',
		'TagWorkConnection',
		'TagWorkCreatorConnection',
		'TagWorkInstance',
		'TagWorkLangPreference',
		'TagWorkMediaConnection',
		'TagWorkParenthood',
		'WikiPage',
		'WorkRelation',
		'WorkSource',
	]

	# Check if there's any data to migrate first
	# This prevents creating an empty revision in fresh databases (e.g., test databases)
	# which would cause PostgreSQL sequence conflicts when tests create their own revisions
	for m in old_models_with_history:
		if apps.get_model('otodb', m).objects.exists():
			break
	else:
		return

	rev = Revision.objects.create(user_id=apps.get_model('account', 'account').objects.first().id)
	for m in old_models_with_history:
		model = apps.get_model('otodb', m)
		if hasattr(model, '_revision_meta'):
			for instance in model.objects.values(
				'pk',
				*model._revision_meta.tracked_fields,
				*[attr for attr in model._revision_meta.entity_attrs if attr != 'self'],
			):
				for field in instance:
					change = RevisionChange.objects.create(
						rev=rev,
						target_type=ContentType.objects.get_for_model(model),
						target_id=instance['pk'],
						target_column=field,
						target_value=instance[field],
					)
					for attr in model._revision_meta.entity_attrs:
						if attr == 'self' or instance[attr]:
							RevisionChangeEntity.objects.create(
								change=change,
								entity_type=ContentType.objects.get_for_model(
									model
									if attr == 'self'
									else model._meta.get_field(attr).related_model
								),
								entity_id=instance['pk' if attr == 'self' else attr],
							)


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0071_allow_null_and_blank_source_title'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='Revision',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('date', models.DateTimeField(auto_now_add=True)),
				('message', models.TextField(null=True)),
				(
					'user',
					models.ForeignKey(
						null=True,
						on_delete=django.db.models.deletion.PROTECT,
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
		migrations.CreateModel(
			name='RevisionChange',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('target_id', models.PositiveBigIntegerField()),
				('deleted', models.BooleanField(default=False)),
				('target_column', models.CharField(max_length=100, null=True)),
				('target_value', models.TextField(null=True)),
				(
					'rev',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.revision'
					),
				),
				(
					'target_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
			],
			options={
				'unique_together': {
					('rev', 'target_type', 'target_id', 'target_column')
				},
			},
		),
		migrations.CreateModel(
			name='RevisionChangeEntity',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('entity_id', models.PositiveBigIntegerField()),
				(
					'change',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.revisionchange',
					),
				),
				(
					'entity_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
			],
			options={
				'unique_together': {('change', 'entity_type', 'entity_id')},
			},
		),
		migrations.RunPython(initial_revision, migrations.RunPython.noop),
		migrations.AlterModelOptions(
			name='tagsong',
			options={},
		),
		migrations.AlterModelManagers(
			name='worksource',
			managers=[
				('active_objects', django.db.models.manager.Manager()),
			],
		),
		migrations.AddField(
			model_name='worksourcerejection',
			name='date',
			field=models.DateTimeField(
				auto_now_add=True, default=django.utils.timezone.now
			),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name='mediasongconnection',
			name='song',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.mediasong'
			),
		),
		migrations.AlterField(
			model_name='songrelation',
			name='A',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='relation_A',
				to='otodb.mediasong',
			),
		),
		migrations.AlterField(
			model_name='songrelation',
			name='B',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='relation_B',
				to='otodb.mediasong',
			),
		),
		migrations.AlterField(
			model_name='tagworkconnection',
			name='tag',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.AlterField(
			model_name='tagworkcreatorconnection',
			name='tag',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.AlterField(
			model_name='tagworklangpreference',
			name='tag',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.AlterField(
			model_name='tagworkmediaconnection',
			name='tag',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.AlterField(
			model_name='wikipage',
			name='tag',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE, to='otodb.tagwork'
			),
		),
		migrations.AlterField(
			model_name='workrelation',
			name='A',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='relation_A',
				to='otodb.mediawork',
			),
		),
		migrations.AlterField(
			model_name='workrelation',
			name='B',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='relation_B',
				to='otodb.mediawork',
			),
		),
		migrations.AlterField(
			model_name='worksource',
			name='media',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to='otodb.mediawork',
			),
		),
		migrations.RemoveField(
			model_name='historicalmediasong_tags',
			name='history',
		),
		migrations.RemoveField(
			model_name='historicalmediasong_tags',
			name='mediasong',
		),
		migrations.RemoveField(
			model_name='historicalmediasong_tags',
			name='tagsong',
		),
		migrations.RemoveField(
			model_name='historicalmediasongconnection',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicalmediasongconnection',
			name='song',
		),
		migrations.RemoveField(
			model_name='historicalmediawork',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicalmediawork',
			name='moved_to',
		),
		migrations.RemoveField(
			model_name='historicalmediawork',
			name='thumbnail_source',
		),
		migrations.RemoveField(
			model_name='historicaltagworkinstance',
			name='history',
		),
		migrations.RemoveField(
			model_name='historicalsongrelation',
			name='A',
		),
		migrations.RemoveField(
			model_name='historicalsongrelation',
			name='B',
		),
		migrations.RemoveField(
			model_name='historicalsongrelation',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicaltagsong',
			name='aliased_to',
		),
		migrations.RemoveField(
			model_name='historicaltagsong',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicaltagsong',
			name='parent',
		),
		migrations.RemoveField(
			model_name='historicaltagwork',
			name='aliased_to',
		),
		migrations.RemoveField(
			model_name='historicaltagwork',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicaltagworkconnection',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicaltagworkconnection',
			name='tag',
		),
		migrations.RemoveField(
			model_name='historicaltagworkcreatorconnection',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicaltagworkcreatorconnection',
			name='tag',
		),
		migrations.RemoveField(
			model_name='historicaltagworkinstance',
			name='work',
		),
		migrations.RemoveField(
			model_name='historicaltagworkinstance',
			name='work_tag',
		),
		migrations.RemoveField(
			model_name='historicaltagworklangpreference',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicaltagworklangpreference',
			name='tag',
		),
		migrations.RemoveField(
			model_name='historicaltagworkmediaconnection',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicaltagworkmediaconnection',
			name='tag',
		),
		migrations.RemoveField(
			model_name='historicaltagworkparenthood',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicaltagworkparenthood',
			name='parent',
		),
		migrations.RemoveField(
			model_name='historicaltagworkparenthood',
			name='tag',
		),
		migrations.RemoveField(
			model_name='historicalwikipage',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicalwikipage',
			name='tag',
		),
		migrations.RemoveField(
			model_name='historicalworkrelation',
			name='A',
		),
		migrations.RemoveField(
			model_name='historicalworkrelation',
			name='B',
		),
		migrations.RemoveField(
			model_name='historicalworkrelation',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicalworksource',
			name='added_by',
		),
		migrations.RemoveField(
			model_name='historicalworksource',
			name='history_user',
		),
		migrations.RemoveField(
			model_name='historicalworksource',
			name='media',
		),
		migrations.DeleteModel(
			name='HistoricalMediaSong',
		),
		migrations.DeleteModel(
			name='HistoricalMediaSong_tags',
		),
		migrations.DeleteModel(
			name='HistoricalMediaSongConnection',
		),
		migrations.DeleteModel(
			name='HistoricalMediaWork',
		),
		migrations.DeleteModel(
			name='HistoricalSongRelation',
		),
		migrations.DeleteModel(
			name='HistoricalTagSong',
		),
		migrations.DeleteModel(
			name='HistoricalTagWork',
		),
		migrations.DeleteModel(
			name='HistoricalTagWorkConnection',
		),
		migrations.DeleteModel(
			name='HistoricalTagWorkCreatorConnection',
		),
		migrations.DeleteModel(
			name='HistoricalTagWorkInstance',
		),
		migrations.DeleteModel(
			name='HistoricalTagWorkLangPreference',
		),
		migrations.DeleteModel(
			name='HistoricalTagWorkMediaConnection',
		),
		migrations.DeleteModel(
			name='HistoricalTagWorkParenthood',
		),
		migrations.DeleteModel(
			name='HistoricalWikiPage',
		),
		migrations.DeleteModel(
			name='HistoricalWorkRelation',
		),
		migrations.DeleteModel(
			name='HistoricalWorkSource',
		),
	]
