# Generated by Django 5.2.7 on 2025-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0073_alter_revision_user'),
	]

	operations = [
		migrations.AlterField(
			model_name='revision',
			name='message',
			field=models.TextField(default=''),
		),
	]
