# Generated by Django 5.2.7 on 2025-11-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0075_revisionchangeentity_route'),
	]

	operations = [
		migrations.AddField(
			model_name='revisionchange',
			name='restored',
			field=models.BooleanField(default=False),
		),
		migrations.AddConstraint(
			model_name='revisionchange',
			constraint=models.CheckConstraint(
				condition=models.Q(
					('deleted', True), ('restored', True), _negated=True
				),
				name='revisionchange_cannot_be_both_delete_and_restore',
			),
		),
		migrations.AddConstraint(
			model_name='revisionchange',
			constraint=models.UniqueConstraint(
				condition=models.Q(('deleted', True)),
				fields=('target_type', 'target_id'),
				name='revisionchange_model_can_only_be_deleted_once',
			),
		),
		migrations.AddConstraint(
			model_name='revisionchange',
			constraint=models.UniqueConstraint(
				condition=models.Q(('restored', True)),
				fields=('target_type', 'target_id'),
				name='revisionchange_model_can_only_be_restored_once',
			),
		),
	]
