# Generated by Django 5.2.9 on 2025-12-17 04:14

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0076_revisionchange_restored_and_more'),
	]

	operations = [
		migrations.AlterModelManagers(
			name='mediawork',
			managers=[
				('active_objects', django.db.models.manager.Manager()),
			],
		),
		migrations.AlterField(
			model_name='userpreferences',
			name='theme',
			field=models.IntegerField(
				choices=[(0, 'Default'), (1, 'Aniki'), (2, 'otogroove')], default=0
			),
		),
	]
