# Generated by Django 5.2.9 on 2026-01-16 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0080_alter_historicalworksource_platform_and_more'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='Notification',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'message',
					models.IntegerField(choices=[(0, 'Reply'), (1, 'Entity Edited')]),
				),
				('entity_id', models.PositiveBigIntegerField()),
				('dismissed', models.BooleanField(default=False)),
				(
					'entity_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
				(
					'target',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
	]
