# Generated by Django 5.2.9 on 2026-01-18 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0081_notification'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AlterField(
			model_name='notification',
			name='target',
			field=models.ForeignKey(
				on_delete=django.db.models.deletion.CASCADE,
				related_name='notifs',
				to=settings.AUTH_USER_MODEL,
			),
		),
		migrations.CreateModel(
			name='Subscription',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('entity_id', models.PositiveBigIntegerField()),
				(
					'entity_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
				(
					'subscriber',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
	]
