# Generated by Django 5.2.9 on 2026-01-18 06:52

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0082_alter_notification_target_subscription'),
	]

	operations = [
		migrations.RemoveField(
			model_name='notification',
			name='message',
		),
	]
