# Generated by Django 5.2.9 on 2026-01-18 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('django_comments_xtd', '0008_auto_20200920_2037'),
		('otodb', '0083_remove_notification_message'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.RemoveField(
			model_name='notification',
			name='entity_id',
		),
		migrations.RemoveField(
			model_name='notification',
			name='entity_type',
		),
		migrations.AddField(
			model_name='notification',
			name='comment',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to='django_comments_xtd.xtdcomment',
			),
		),
		migrations.AddField(
			model_name='notification',
			name='revision',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to='otodb.revision',
			),
		),
		migrations.AddConstraint(
			model_name='notification',
			constraint=models.CheckConstraint(
				condition=models.Q(
					('revision__isnull', True),
					('comment__isnull', True),
					_connector='XOR',
				),
				name='notification_union',
			),
		),
		migrations.AddConstraint(
			model_name='subscription',
			constraint=models.UniqueConstraint(
				fields=('subscriber', 'entity_type', 'entity_id'),
				name='unique_subscription',
			),
		),
	]
