# Generated by Django 5.2.9 on 2026-01-25 19:11

from django.db import migrations


def nicopedia_add_v(apps, schema_editor):
	from django.db.models import CharField, Value
	from django.db.models.functions import Concat
	from otodb.models.enums import TagWorkConnectionTypes

	TagWorkConnection = apps.get_model('otodb', 'TagWorkConnection')
	TagWorkConnection.objects.filter(site=TagWorkConnectionTypes.NICOPEDIA).update(
		content_id=Concat(Value('a/'), 'content_id', output_field=CharField())
	)


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0084_remove_notification_entity_id_and_more'),
	]

	operations = [
		migrations.RunPython(nicopedia_add_v),
	]
