# Generated by Django 5.2.9 on 2026-01-25 20:10

import dirtyfields.dirtyfields
import django.db.models.deletion
import tagulous.models.fields
from django.db import migrations, models


def move_tsi(apps, schema_editor):
	TagSong = apps.get_model('otodb', 'TagSong')
	TagSongInstance = apps.get_model('otodb', 'TagSongInstance')

	for tag in TagSong.objects.all():
		for song in tag.songs.all():
			TagSongInstance.objects.create(song_tag=tag, song=song)


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0085_auto_20260125_1311'),
	]

	operations = [
		migrations.AlterUniqueTogether(
			name='tagsonglangpreference',
			unique_together={('tag', 'lang')},
		),
		migrations.CreateModel(
			name='TagSongInstance',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'song',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.mediasong',
					),
				),
				(
					'song_tag',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.tagsong'
					),
				),
			],
			options={
				'unique_together': {('song', 'song_tag')},
			},
			bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
		),
		migrations.AddField(
			model_name='mediasong',
			name='tags_asdf',
			field=tagulous.models.fields.TagField(
				_set_tag_meta=True,
				case_sensitive=False,
				force_lowercase=True,
				help_text='Enter a comma-separated tag string',
				protect_all=True,
				related_name='songs_asdf',
				through='otodb.TagSongInstance',
				to='otodb.tagsong',
			),
		),
		migrations.RunPython(move_tsi),
		migrations.RemoveField(
			model_name='mediasong',
			name='tags',
		),
		migrations.RenameField(
			model_name='mediasong',
			old_name='tags_asdf',
			new_name='tags',
		),
		migrations.AlterField(
			model_name='mediasong',
			name='tags',
			field=tagulous.models.fields.TagField(
				_set_tag_meta=True,
				case_sensitive=False,
				force_lowercase=True,
				help_text='Enter a comma-separated tag string',
				protect_all=True,
				related_name='songs',
				through='otodb.TagSongInstance',
				to='otodb.tagsong',
			),
		),
	]
