# Generated by Django 5.2.9 on 2026-02-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0086_alter_tagsonglangpreference_unique_together_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='revisionchangeentity',
			name='route',
			field=models.IntegerField(
				choices=[
					(0, 'Unknown'),
					(1, 'Tag Work Alias'),
					(2, 'Tag Work Unalias'),
					(3, 'Tag Work Delete'),
					(4, 'Tag Work Update'),
					(5, 'Tag Work Set Base'),
					(6, 'Tag Work Add Language Preference'),
					(7, 'Tag Work Edit Wiki'),
					(8, 'Tag Work Edit Connections'),
					(20, 'Song Tag Update'),
					(21, 'Song Tag Set Tags'),
					(22, 'Song Tag Alias'),
					(23, 'Song Tag Unalias'),
					(24, 'Song Tag Delete'),
					(25, 'Song Tag Set Base'),
					(26, 'Song Tag Add Language Preference'),
					(30, 'Song Relation Create'),
					(31, 'Song Relation Delete'),
					(40, 'Media Work Delete'),
					(41, 'Media Work Set Tags'),
					(42, 'Media Work Remove Tag'),
					(43, 'Media Work Update Creator Roles'),
					(44, 'Media Work Toggle Sample'),
					(45, 'Media Work Update'),
					(46, 'Media Work Merge'),
					(50, 'Work Relation Create'),
					(51, 'Work Relation Delete'),
					(60, 'Work Source Create'),
					(61, 'Work Source Unbind'),
					(62, 'Work Source Set Origin'),
					(63, 'Work Source Refresh'),
					(64, 'Work Source Assign'),
					(65, 'Work Source Reject'),
					(100, 'Rollback'),
				],
				default=0,
			),
		),
		migrations.AddConstraint(
			model_name='tagsong',
			constraint=models.CheckConstraint(
				condition=models.Q(('parent_id', models.F('id')), _negated=True),
				name='tagsong_parenthood_nonreflexive',
				violation_error_message='tag cannot be own parent',
			),
		),
	]
