# Generated by Django 5.2.9 on 2026-02-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0087_alter_revisionchangeentity_route_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='worksource',
			name='platform',
			field=models.IntegerField(
				choices=[
					(1, 'YouTube'),
					(2, 'Niconico'),
					(3, 'Bilibili'),
					(4, 'SoundCloud'),
					(5, 'Twitter'),
					(6, 'AcFun'),
				]
			),
		),
	]
