# Generated by Django 5.2.9 on 2026-02-25 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('django_comments_xtd', '0008_auto_20200920_2037'),
		('otodb', '0088_alter_worksource_platform'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.RemoveConstraint(
			model_name='notification',
			name='notification_union',
		),
		migrations.AddField(
			model_name='notification',
			name='post',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to='otodb.post',
			),
		),
		migrations.AddConstraint(
			model_name='notification',
			constraint=models.CheckConstraint(
				condition=(
					models.Q(
						revision__isnull=False,
						comment__isnull=True,
						post__isnull=True,
					)
					| models.Q(
						revision__isnull=True,
						comment__isnull=False,
						post__isnull=True,
					)
					| models.Q(
						revision__isnull=True,
						comment__isnull=True,
						post__isnull=False,
					)
				),
				name='notification_union',
			),
		),
	]
