# Generated by Django 5.2.9 on 2026-02-27 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	replaces = [
		('otodb', '0089_remove_notification_notification_union_and_more'),
		('otodb', '0090_alter_postcontent_page_and_more'),
	]

	dependencies = [
		('django_comments_xtd', '0008_auto_20200920_2037'),
		('otodb', '0088_alter_worksource_platform'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.RemoveConstraint(
			model_name='notification',
			name='notification_union',
		),
		migrations.AddField(
			model_name='notification',
			name='post',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to='otodb.post',
			),
		),
		migrations.AddConstraint(
			model_name='notification',
			constraint=models.CheckConstraint(
				condition=models.Q(
					models.Q(
						('comment__isnull', True),
						('post__isnull', True),
						('revision__isnull', False),
					),
					models.Q(
						('comment__isnull', False),
						('post__isnull', True),
						('revision__isnull', True),
					),
					models.Q(
						('comment__isnull', True),
						('post__isnull', False),
						('revision__isnull', True),
					),
					_connector='OR',
				),
				name='notification_union',
			),
		),
		migrations.AlterField(
			model_name='postcontent',
			name='page',
			field=models.TextField(),
		),
		migrations.AlterField(
			model_name='postcontent',
			name='page_rendered',
			field=models.TextField(blank=True, default=''),
		),
		migrations.AlterField(
			model_name='wikipage',
			name='page',
			field=models.TextField(),
		),
		migrations.AlterField(
			model_name='wikipage',
			name='page_rendered',
			field=models.TextField(blank=True, default=''),
		),
	]
