# Generated by Django 5.2.9 on 2026-03-12 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0089_remove_notification_notification_union_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='post',
			name='category',
			field=models.IntegerField(
				choices=[
					(0, 'Announcement'),
					(1, 'Feature Request'),
					(2, 'Bug Report'),
					(3, 'Gardening'),
					(4, 'General'),
				]
			),
		),
		migrations.CreateModel(
			name='EntityLink',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('entity_id', models.PositiveBigIntegerField()),
				(
					'entity_type',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
				(
					'post',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to='otodb.post'
					),
				),
			],
			options={
				'constraints': [
					models.UniqueConstraint(
						fields=('entity_type', 'entity_id', 'post'),
						name='entitylink_unique_post',
					)
				],
			},
		),
	]
