# Generated by Django 5.2.9 on 2026-03-12 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('django_comments_xtd', '0008_auto_20200920_2037'),
		('otodb', '0090_alter_post_category_entitylink'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddField(
			model_name='post',
			name='edited_at',
			field=models.DateTimeField(blank=True, null=True),
		),
		migrations.AddField(
			model_name='post',
			name='edited_by',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name='edited_posts',
				to=settings.AUTH_USER_MODEL,
			),
		),
		migrations.CreateModel(
			name='CommentMeta',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('edited_at', models.DateTimeField(blank=True, null=True)),
				(
					'comment',
					models.OneToOneField(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='meta',
						to='django_comments_xtd.xtdcomment',
					),
				),
				(
					'edited_by',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='edited_comments',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
		),
	]
