# Generated by Django 5.2.9 on 2026-03-13 14:01

from django.db import migrations


def consolidate_routes(apps, schema_editor):
	RevisionChangeEntity = apps.get_model('otodb', 'RevisionChangeEntity')

	RevisionChangeEntity.objects.filter(route__in=[5, 6]).update(route=2)
	RevisionChangeEntity.objects.filter(route__in=[25, 26]).update(route=22)
	RevisionChangeEntity.objects.filter(route=31).update(route=30)
	RevisionChangeEntity.objects.filter(route=51).update(route=50)
	RevisionChangeEntity.objects.filter(route__in=[43, 44]).update(route=41)


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0091_post_edited_at_post_edited_by_commentmeta'),
	]

	operations = [
		migrations.RunPython(consolidate_routes),
	]
