# Generated by Django 6.0.2 on 2026-03-17 21:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def _create_moderation_events_view(apps, schema_editor):
	"""Create the moderation_events VIEW, resolving the account table dynamically."""
	Account = apps.get_model(settings.AUTH_USER_MODEL)
	account_table = Account._meta.db_table
	schema_editor.execute(f"""
        CREATE VIEW moderation_events AS
        SELECT 'flag' AS event_type, f.id AS event_id, f.work_id,
               CAST(NULL AS bigint) AS source_id, f.by_id, u.username AS by_username,
               f.reason, f.status, f.date AS event_at
        FROM otodb_workflag f
        JOIN {account_table} u ON u.id = f.by_id
        UNION ALL
        SELECT 'appeal', a.id, a.work_id, CAST(NULL AS bigint), a.by_id, u.username,
               a.reason, a.status, a.date
        FROM otodb_workappeal a
        JOIN {account_table} u ON u.id = a.by_id
        UNION ALL
        SELECT 'disapproval', d.id, d.work_id, CAST(NULL AS bigint), d.by_id, u.username,
               d.reason, CAST(NULL AS integer), d.date
        FROM otodb_workdisapproval d
        JOIN {account_table} u ON u.id = d.by_id
        UNION ALL
        SELECT 'approval', ap.id, ap.work_id, CAST(NULL AS bigint), ap.by_id, u.username,
               '' AS reason, CAST(NULL AS integer), ap.date
        FROM otodb_workapproval ap
        JOIN {account_table} u ON u.id = ap.by_id
        UNION ALL
        SELECT 'mod_action', m.id, m.work_id, m.source_id, m.by_id, u.username,
               m.description, m.category, m.date
        FROM otodb_modaction m
        JOIN {account_table} u ON u.id = m.by_id
    """)


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0093_alter_revisionchangeentity_route_and_more'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='ModerationEvent',
			fields=[
				('event_type', models.CharField(max_length=20)),
				('event_id', models.IntegerField(primary_key=True, serialize=False)),
				('work_id', models.IntegerField(null=True)),
				('source_id', models.IntegerField(null=True)),
				('by_id', models.IntegerField()),
				('by_username', models.CharField(max_length=150)),
				('reason', models.CharField(max_length=1000)),
				('status', models.IntegerField(null=True)),
				('event_at', models.DateTimeField()),
			],
			options={
				'db_table': 'moderation_events',
				'managed': False,
			},
		),
		migrations.AddField(
			model_name='mediawork',
			name='created_at',
			field=models.DateTimeField(
				auto_now_add=True, db_index=True, default=django.utils.timezone.now
			),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='mediawork',
			name='status',
			field=models.IntegerField(
				choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Unapproved')], default=1
			),
		),
		migrations.AddField(
			model_name='worksource',
			name='created_at',
			field=models.DateTimeField(
				auto_now_add=True, default=django.utils.timezone.now
			),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='worksource',
			name='is_pending',
			field=models.BooleanField(default=False),
		),
		migrations.AlterField(
			model_name='revisionchangeentity',
			name='route',
			field=models.IntegerField(
				choices=[
					(0, 'Unknown'),
					(1, 'Tag Work Alias'),
					(2, 'Tag Work Alias Control'),
					(3, 'Tag Work Delete'),
					(4, 'Tag Work Update'),
					(5, 'DEPRECATED - Tag Work Set Base'),
					(6, 'DEPRECATED - Tag Work Add Language Preference'),
					(7, 'Tag Work Edit Wiki'),
					(8, 'Tag Work Edit Connections'),
					(20, 'Song Tag Update'),
					(21, 'Song Tag Set Tags'),
					(22, 'Song Tag Alias'),
					(23, 'Song Tag Alias Control'),
					(24, 'Song Tag Delete'),
					(25, 'DEPRECATED -Song Tag Set Base'),
					(26, 'DEPRECATED - Song Tag Add Language Preference'),
					(30, 'Song Relation Control'),
					(31, 'DEPRECATED - Song Relation Delete'),
					(40, 'Media Work Delete'),
					(41, 'Media Work Set Tags'),
					(42, 'Media Work Remove Tag'),
					(43, 'DEPRECATED - Media Work Update Creator Roles'),
					(44, 'DEPRECATED - Media Work Toggle Sample'),
					(45, 'Media Work Update'),
					(46, 'Media Work Merge'),
					(47, 'Media Work Create'),
					(50, 'Work Relation Control'),
					(51, 'DEPRECATED - Work Relation Delete'),
					(60, 'Work Source Create'),
					(61, 'Work Source Unbind'),
					(62, 'Work Source Set Origin'),
					(63, 'Work Source Refresh'),
					(64, 'Work Source Assign'),
					(65, 'Work Source Reject'),
					(66, 'Work Source Update'),
					(100, 'Rollback'),
				],
				default=0,
			),
		),
		migrations.CreateModel(
			name='ModAction',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'category',
					models.IntegerField(
						choices=[
							(1, 'Work Delisted'),
							(10, 'Source Approved'),
							(11, 'Source Rejected'),
						]
					),
				),
				(
					'description',
					models.CharField(blank=True, default='', max_length=1000),
				),
				('date', models.DateTimeField(auto_now_add=True, db_index=True)),
				(
					'by',
					models.ForeignKey(
						on_delete=django.db.models.deletion.RESTRICT,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'source',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						to='otodb.worksource',
					),
				),
				(
					'work',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.mediawork',
					),
				),
			],
			options={
				'ordering': ['-date'],
			},
		),
		migrations.CreateModel(
			name='WorkAppeal',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('reason', models.CharField(max_length=1000)),
				(
					'status',
					models.IntegerField(
						choices=[(0, 'Pending'), (1, 'Succeeded'), (2, 'Rejected')],
						default=0,
					),
				),
				('date', models.DateTimeField(auto_now_add=True)),
				(
					'by',
					models.ForeignKey(
						on_delete=django.db.models.deletion.RESTRICT,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'work',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='appeals',
						to='otodb.mediawork',
					),
				),
			],
		),
		migrations.CreateModel(
			name='WorkApproval',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('date', models.DateTimeField(auto_now_add=True)),
				(
					'by',
					models.ForeignKey(
						on_delete=django.db.models.deletion.RESTRICT,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'work',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='approvals',
						to='otodb.mediawork',
					),
				),
			],
			options={
				'ordering': ['-date'],
			},
		),
		migrations.CreateModel(
			name='WorkDisapproval',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('reason', models.CharField(max_length=1000)),
				('date', models.DateTimeField(auto_now_add=True)),
				(
					'by',
					models.ForeignKey(
						on_delete=django.db.models.deletion.RESTRICT,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'work',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='disapprovals',
						to='otodb.mediawork',
					),
				),
			],
		),
		migrations.CreateModel(
			name='WorkFlag',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				('reason', models.CharField(max_length=1000)),
				(
					'status',
					models.IntegerField(
						choices=[(0, 'Pending'), (1, 'Succeeded'), (2, 'Rejected')],
						default=0,
					),
				),
				('date', models.DateTimeField(auto_now_add=True)),
				(
					'by',
					models.ForeignKey(
						on_delete=django.db.models.deletion.RESTRICT,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'work',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='flags',
						to='otodb.mediawork',
					),
				),
			],
		),
		migrations.DeleteModel(
			name='WorkSourceRejection',
		),
		migrations.AddConstraint(
			model_name='workappeal',
			constraint=models.UniqueConstraint(
				condition=models.Q(('status', 0)),
				fields=('work',),
				name='unique_pending_appeal_per_work',
				violation_error_message='A pending appeal already exists for this work',
			),
		),
		migrations.AlterUniqueTogether(
			name='workdisapproval',
			unique_together={('work', 'by')},
		),
		migrations.AddConstraint(
			model_name='workflag',
			constraint=models.UniqueConstraint(
				condition=models.Q(('status', 0)),
				fields=('work',),
				name='unique_pending_flag_per_work',
				violation_error_message='A pending flag already exists for this work',
			),
		),
		migrations.RunPython(
			_create_moderation_events_view,
			reverse_code=lambda apps, se: se.execute(
				'DROP VIEW IF EXISTS moderation_events'
			),
		),
	]
