# Generated by Django 6.0.3 on 2026-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0093_alter_revisionchangeentity_route_and_more'),
	]

	operations = [
		migrations.AlterField(
			model_name='revisionchangeentity',
			name='route',
			field=models.IntegerField(
				choices=[
					(0, 'Unknown'),
					(1, 'Tag Work Alias'),
					(2, 'Tag Work Alias Control'),
					(3, 'Tag Work Delete'),
					(4, 'Tag Work Update'),
					(5, 'DEPRECATED - Tag Work Set Base'),
					(6, 'DEPRECATED - Tag Work Add Language Preference'),
					(7, 'Tag Work Edit Wiki'),
					(8, 'Tag Work Edit Connections'),
					(20, 'Song Tag Update'),
					(21, 'Song Tag Set Tags'),
					(22, 'Song Tag Alias'),
					(23, 'Song Tag Alias Control'),
					(24, 'Song Tag Delete'),
					(25, 'DEPRECATED -Song Tag Set Base'),
					(26, 'DEPRECATED - Song Tag Add Language Preference'),
					(30, 'Song Relation Control'),
					(31, 'DEPRECATED - Song Relation Delete'),
					(40, 'Media Work Delete'),
					(41, 'Media Work Set Tags'),
					(42, 'Media Work Remove Tag'),
					(43, 'DEPRECATED - Media Work Update Creator Roles'),
					(44, 'DEPRECATED - Media Work Toggle Sample'),
					(45, 'Media Work Update'),
					(46, 'Media Work Merge'),
					(47, 'Media Work Create'),
					(50, 'Work Relation Control'),
					(51, 'DEPRECATED - Work Relation Delete'),
					(60, 'Work Source Create'),
					(61, 'Work Source Unbind'),
					(62, 'Work Source Set Origin'),
					(63, 'Work Source Refresh'),
					(64, 'Work Source Assign'),
					(65, 'Work Source Reject'),
					(66, 'Work Source Update'),
					(100, 'Rollback'),
				],
				default=0,
			),
		),
	]
