# Generated by Django 6.0.2 on 2026-03-21 01:51

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0094_alter_revisionchangeentity_route'),
	]

	operations = [
		migrations.RemoveField(
			model_name='tagworkinstance',
			name='instance_imported_from_source',
		),
	]
