# Generated by Django 6.0.2 on 2026-03-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0095_remove_tagworkinstance_imported_from_source'),
	]

	operations = [
		migrations.AlterField(
			model_name='userrequest',
			name='command',
			field=models.IntegerField(
				choices=[
					(1, 'Tagwork Alias'),
					(2, 'Tagwork Unalias'),
					(3, 'Tagwork Deprecate'),
					(4, 'Tagwork Undeprecate'),
					(5, 'Tagwork Parent'),
					(6, 'Tagwork Unparent'),
				]
			),
		),
	]
