# Generated by Django 6.0.2 on 2026-03-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0096_remove_attach_tag_bulk_requests'),
	]

	operations = [
		migrations.AlterField(
			model_name='mediasongconnection',
			name='site',
			field=models.IntegerField(
				choices=[
					(0, 'VGMdb'),
					(1, 'VocaDB'),
					(2, 'Discogs'),
					(3, 'MusicBrainz'),
					(4, 'Rate Your Music'),
					(5, 'dojin-music.info'),
					(6, 'TouhouDB'),
					(20, 'RemyWiki'),
					(21, 'Silent Blue'),
					(22, 'Zenius -I- vanisher.com'),
					(30, 'NND Medley Wiki'),
					(40, 'The Mod Archive'),
				]
			),
		),
	]
