# Generated by Django 6.0.4 on 2026-04-12 19:56

import tagulous.models.fields
from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0098_tag_display_names'),
	]

	operations = [
		migrations.AlterField(
			model_name='mediasong',
			name='tags',
			field=tagulous.models.fields.TagField(
				_set_tag_meta=True,
				case_sensitive=False,
				force_lowercase=False,
				help_text='Enter a comma-separated tag string',
				protect_all=True,
				related_name='songs',
				through='otodb.TagSongInstance',
				to='otodb.tagsong',
			),
		),
		migrations.AlterField(
			model_name='mediawork',
			name='tags',
			field=tagulous.models.fields.TagField(
				_set_tag_meta=True,
				case_sensitive=False,
				force_lowercase=False,
				help_text='Enter a comma-separated tag string',
				protect_all=True,
				related_name='works',
				through='otodb.TagWorkInstance',
				to='otodb.tagwork',
			),
		),
	]
