# Generated by Django 6.0.4 on 2026-04-20 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def move_prefs(apps, schema_editor):
	UserPreferences = apps.get_model('otodb', 'UserPreferences')
	UserPreference = apps.get_model('otodb', 'UserPreference')
	from otodb.models.enums import LanguageTypes, Preferences

	for pref in UserPreferences.objects.all():
		if pref.language != LanguageTypes.NOT_APPLICABLE:
			UserPreference.objects.create(
				user=pref.user,
				setting=Preferences.LANGUAGE,
				value=pref.language,
			)
		UserPreference.objects.create(
			user=pref.user,
			setting=Preferences.THEME,
			value=pref.theme,
		)


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0102_post_closed_at'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name='UserPreference',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'setting',
					models.IntegerField(choices=[(1, 'Language'), (2, 'Theme')]),
				),
				('value', models.IntegerField()),
				(
					'user',
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name='preferences',
						to=settings.AUTH_USER_MODEL,
					),
				),
			],
			options={
				'constraints': [
					models.UniqueConstraint(
						fields=('user', 'setting'),
						name='userpreference_single_value_for_setting',
					)
				],
			},
		),
		migrations.RunPython(move_prefs, reverse_code=migrations.RunPython.noop),
		migrations.DeleteModel(
			name='UserPreferences',
		),
	]
