# Generated by Django 6.0.3 on 2026-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0103_userpreference'),
	]

	operations = [
		migrations.AddField(
			model_name='notification',
			name='reason',
			field=models.IntegerField(
				choices=[(0, 'Reply'), (1, 'Mention'), (2, 'Thread Linked')],
				default=0,
			),
		),
	]
