# Generated by Django 6.0.2 on 2026-03-19 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0104_notification_reason_and_order'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AlterModelManagers(
			name='mediawork',
			managers=[],
		),
		migrations.AddField(
			model_name='mediawork',
			name='created_at',
			field=models.DateTimeField(
				auto_now_add=True, db_index=True, default=django.utils.timezone.now
			),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='mediawork',
			name='status',
			field=models.IntegerField(
				blank=True,
				choices=[(0, 'Pending'), (1, 'Succeeded'), (2, 'Rejected')],
				null=True,
			),
		),
		migrations.AddField(
			model_name='worksource',
			name='created_at',
			field=models.DateTimeField(
				auto_now_add=True, default=django.utils.timezone.now
			),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='worksource',
			name='is_pending',
			field=models.BooleanField(default=False),
		),
		migrations.DeleteModel(
			name='WorkSourceRejection',
		),
		migrations.CreateModel(
			name='ModerationEvent',
			fields=[
				(
					'id',
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name='ID',
					),
				),
				(
					'event_type',
					models.IntegerField(
						choices=[
							(0, 'Flag'),
							(1, 'Appeal'),
							(2, 'Disapproval'),
							(3, 'Approval'),
							(4, 'Mod Action'),
						]
					),
				),
				('reason', models.CharField(blank=True, default='', max_length=1000)),
				('status', models.IntegerField(blank=True, null=True)),
				('date', models.DateTimeField(auto_now_add=True, db_index=True)),
				(
					'by',
					models.ForeignKey(
						on_delete=django.db.models.deletion.RESTRICT,
						to=settings.AUTH_USER_MODEL,
					),
				),
				(
					'source',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name='moderation_events',
						to='otodb.worksource',
					),
				),
				(
					'work',
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.CASCADE,
						related_name='moderation_events',
						to='otodb.mediawork',
					),
				),
			],
			options={
				'ordering': ['-date'],
			},
		),
		migrations.AddIndex(
			model_name='moderationevent',
			index=models.Index(
				fields=['event_type', 'status'],
				name='otodb_moder_event_t_e72254_idx',
			),
		),
		migrations.AddIndex(
			model_name='moderationevent',
			index=models.Index(
				fields=['work', 'event_type'],
				name='otodb_moder_work_id_e763b1_idx',
			),
		),
		migrations.AddConstraint(
			model_name='moderationevent',
			constraint=models.UniqueConstraint(
				condition=models.Q(('event_type__in', [0, 1]), ('status', 0)),
				fields=('work',),
				name='unique_pending_moderation_per_work',
				violation_error_message='This work already has a pending flag or appeal',
			),
		),
		migrations.AddConstraint(
			model_name='moderationevent',
			constraint=models.UniqueConstraint(
				condition=models.Q(('event_type', 2)),
				fields=('work', 'by'),
				name='unique_disapproval_per_work_per_user',
			),
		),
	]
