# Generated by Django 6.0.4 on 2026-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0105_moderationevent_mediawork_created_at_and_more'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='tagwork',
			options={
				'ordering': [
					models.Case(
						models.When(category=1, then=models.Value(0)),
						models.When(category=4, then=models.Value(10)),
						models.When(category=6, then=models.Value(11)),
						models.When(category=3, then=models.Value(20)),
						models.When(category=2, then=models.Value(30)),
						models.When(category=5, then=models.Value(1000)),
						models.When(category=0, then=models.Value(9999)),
						default=models.Value(999),
						output_field=models.IntegerField(),
					),
					'name',
				]
			},
		),
		migrations.AlterField(
			model_name='tagwork',
			name='category',
			field=models.IntegerField(
				choices=[
					(0, 'Uncategorized'),
					(1, 'Event'),
					(2, 'Song'),
					(3, 'Source'),
					(4, 'Creator'),
					(5, 'Meta'),
					(6, 'Media'),
					(7, 'General'),
				],
				default=0,
			),
		),
	]
