# Generated by Django 6.0.4 on 2026-04-24 00:44

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0106_tagwork_add_new_general_category'),
	]

	operations = [
		migrations.AddField(
			model_name='notification',
			name='created_at',
			field=models.DateTimeField(
				auto_now_add=True,
				db_index=True,
				default=datetime.datetime(
					2026, 4, 20, 0, 0, tzinfo=datetime.timezone.utc
				),
			),
			preserve_default=False,
		),
	]
