# Generated by Django 6.0.4 on 2026-04-24 17:44

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0001_initial_squashed_0107'),
	]

	operations = [
		migrations.AlterModelManagers(
			name='worksource',
			managers=[],
		),
	]
