# Generated by Django 6.0.4 on 2026-04-30 00:28
from urllib.parse import unquote

from django.db import migrations
from django.utils.encoding import uri_to_iri

import otodb.models.fields

CONNECTION_MODELS = [
	'MediaSongConnection',
	'TagWorkConnection',
	'TagWorkMediaConnection',
	'TagWorkCreatorConnection',
	'ProfileConnection',
]

URL_FIELD_COLUMNS = ['url', 'thumbnail_url', 'upstream']

# Accidentally changed in prod oops
EXCLUDED_REVISION_IDS = [44189, 44190]


def forward(apps, schema_editor):
	# Connection content_ids are opaque path segments; full unquote so equivalent
	# values (e.g. 'glory day' vs 'glory%20day') collapse to one canonical form.
	for model_name in CONNECTION_MODELS:
		Model = apps.get_model('otodb', model_name)
		for row in Model.objects.filter(content_id__contains='%').only(
			'id', 'content_id'
		):
			decoded = unquote(row.content_id)
			if decoded != row.content_id:
				row.content_id = decoded
				row.save(update_fields=['content_id'])

	RevisionChange = apps.get_model('otodb', 'RevisionChange')

	# Same treatment for content_id history.
	for row in (
		RevisionChange.objects.filter(
			target_column='content_id', target_value__contains='%'
		)
		.exclude(rev_id__in=EXCLUDED_REVISION_IDS)
		.only('id', 'target_value')
	):
		decoded = unquote(row.target_value)
		if decoded != row.target_value:
			row.target_value = decoded
			row.save(update_fields=['target_value'])

	# URL field history uses uri_to_iri (preserves reserved-character escapes
	# so query-string semantics aren't corrupted). Cheap; zero rows in current
	# data but covers future-proofing.
	for row in (
		RevisionChange.objects.filter(
			target_column__in=URL_FIELD_COLUMNS, target_value__contains='%'
		)
		.exclude(rev_id__in=EXCLUDED_REVISION_IDS)
		.only('id', 'target_value')
	):
		decoded = uri_to_iri(row.target_value)
		if decoded != row.target_value:
			row.target_value = decoded
			row.save(update_fields=['target_value'])


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0108_alter_worksource_managers'),
	]

	operations = [
		migrations.AlterField(
			model_name='mediasongconnection',
			name='content_id',
			field=otodb.models.fields.IRICharField(max_length=1000),
		),
		migrations.AlterField(
			model_name='poolupstream',
			name='upstream',
			field=otodb.models.fields.IRIURLField(),
		),
		migrations.AlterField(
			model_name='profileconnection',
			name='content_id',
			field=otodb.models.fields.IRICharField(max_length=1000),
		),
		migrations.AlterField(
			model_name='tagworkconnection',
			name='content_id',
			field=otodb.models.fields.IRICharField(max_length=1000),
		),
		migrations.AlterField(
			model_name='tagworkcreatorconnection',
			name='content_id',
			field=otodb.models.fields.IRICharField(max_length=1000),
		),
		migrations.AlterField(
			model_name='tagworkmediaconnection',
			name='content_id',
			field=otodb.models.fields.IRICharField(max_length=1000),
		),
		migrations.AlterField(
			model_name='worksource',
			name='thumbnail_url',
			field=otodb.models.fields.IRIURLField(null=True),
		),
		migrations.AlterField(
			model_name='worksource',
			name='url',
			field=otodb.models.fields.IRIURLField(),
		),
		migrations.RunPython(forward, reverse_code=migrations.RunPython.noop),
	]
