# Generated by Django 6.0.4 on 2026-06-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0110_system_route_enum'),
	]

	operations = [
		migrations.AlterField(
			model_name='bulkrequest',
			name='status',
			field=models.IntegerField(
				choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Delisted')], default=0
			),
		),
		migrations.AlterField(
			model_name='mediawork',
			name='status',
			field=models.IntegerField(
				choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Delisted')], default=1
			),
		),
	]
