# Generated by Django 6.0.4 on 2026-05-20 03:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import otodb.models.wiki


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0111_alter_bulkrequest_status_alter_mediawork_status'),
	]

	operations = [
		migrations.AlterUniqueTogether(
			name='wikipage',
			unique_together=set(),
		),
		migrations.AddField(
			model_name='wikipage',
			name='slug',
			field=models.CharField(
				blank=True,
				max_length=255,
				null=True,
				validators=[
					django.core.validators.RegexValidator(regex='^[a-z0-9_-]+$'),
					otodb.models.wiki._validate_wiki_slug,
				],
			),
		),
		migrations.AddField(
			model_name='wikipage',
			name='title',
			field=models.CharField(blank=True, max_length=255, null=True),
		),
		migrations.AddField(
			model_name='wikipage',
			name='work',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to='otodb.mediawork',
			),
		),
		migrations.AlterField(
			model_name='revisionchangeentity',
			name='route',
			field=models.IntegerField(
				choices=[
					(0, 'Unknown'),
					(1, 'Tag Work Alias'),
					(2, 'Tag Work Alias Control'),
					(3, 'Tag Work Delete'),
					(4, 'Tag Work Update'),
					(7, 'Tag Work Edit Wiki'),
					(8, 'Tag Work Edit Connections'),
					(20, 'Song Tag Update'),
					(21, 'Song Tag Set Tags'),
					(22, 'Song Tag Alias'),
					(23, 'Song Tag Alias Control'),
					(24, 'Song Tag Delete'),
					(30, 'Song Relation Control'),
					(40, 'Media Work Delete'),
					(41, 'Media Work Set Tags'),
					(45, 'Media Work Update'),
					(46, 'Media Work Merge'),
					(47, 'Media Work Create'),
					(48, 'Media Work Edit Wiki'),
					(50, 'Work Relation Control'),
					(60, 'Work Source Create'),
					(61, 'Work Source Unbind'),
					(62, 'Work Source Set Origin'),
					(63, 'Work Source Refresh'),
					(64, 'Work Source Assign'),
					(65, 'Work Source Reject'),
					(66, 'Work Source Update'),
					(70, 'Wiki Edit'),
					(100, 'Rollback'),
					(10000, 'System'),
				],
				default=0,
			),
		),
		migrations.AlterField(
			model_name='wikipage',
			name='tag',
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.CASCADE,
				to='otodb.tagwork',
			),
		),
		migrations.AddConstraint(
			model_name='wikipage',
			constraint=models.CheckConstraint(
				condition=models.Q(
					models.Q(
						('slug__isnull', True),
						('tag__isnull', False),
						('work__isnull', True),
					),
					models.Q(
						('slug__isnull', True),
						('tag__isnull', True),
						('work__isnull', False),
					),
					models.Q(
						('slug__isnull', False),
						('tag__isnull', True),
						('work__isnull', True),
					),
					_connector='OR',
				),
				name='wikipage_exactly_one_attachment',
			),
		),
		migrations.AddConstraint(
			model_name='wikipage',
			constraint=models.CheckConstraint(
				condition=models.Q(
					models.Q(('slug__isnull', False), ('title__isnull', False)),
					models.Q(('slug__isnull', True), ('title__isnull', True)),
					_connector='OR',
				),
				name='wikipage_title_iff_slug',
			),
		),
		migrations.AddConstraint(
			model_name='wikipage',
			constraint=models.UniqueConstraint(
				condition=models.Q(('tag__isnull', False)),
				fields=('tag', 'lang'),
				name='unique_wikipage_tag_lang',
			),
		),
		migrations.AddConstraint(
			model_name='wikipage',
			constraint=models.UniqueConstraint(
				condition=models.Q(('work__isnull', False)),
				fields=('work', 'lang'),
				name='unique_wikipage_work_lang',
			),
		),
		migrations.AddConstraint(
			model_name='wikipage',
			constraint=models.UniqueConstraint(
				condition=models.Q(('slug__isnull', False)),
				fields=('slug', 'lang'),
				name='unique_wikipage_slug_lang',
			),
		),
	]
