# Generated by Django 6.0.4 on 2026-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0112_wikipage_attachment'),
	]

	operations = [
		migrations.AlterField(
			model_name='userpreference',
			name='setting',
			field=models.IntegerField(
				choices=[
					(1, 'Language'),
					(2, 'Theme'),
					(3, 'Video Platform'),
					(4, 'Prefer Author Upload'),
				]
			),
		),
	]
