# Generated by Django 6.0.4 on 2026-06-06 11:01

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0115_thread_cleanup'),
	]

	operations = [
		migrations.RemoveField(
			model_name='thread',
			name='lang',
		),
	]
