# Generated by Django 6.0.6 on 2026-06-13 04:05

from django.db import migrations
from django.db.models import F


def twitter_tco_strip(apps, schema_editor):
	import re

	WorkSource = apps.get_model('otodb', 'WorkSource')
	MediaWork = apps.get_model('otodb', 'MediaWork')
	twitter_t_co_re = re.compile(r' ?https://t\.co/[0-9a-zA-Z]{10}$')

	for work in MediaWork.objects.filter(
		worksource__description=F('description'), worksource__platform=5
	).distinct():
		work.description = twitter_t_co_re.sub('', work.description)
		work.save()
	for ws in WorkSource.objects.filter(platform=5):
		ws.description = twitter_t_co_re.sub('', ws.description)
		ws.save()


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0117_remove_thread_lang'),
	]

	operations = [
		migrations.RunPython(twitter_tco_strip),
	]
