# Generated by Django 6.0.6 on 2026-06-10 13:50

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0117_remove_thread_lang'),
	]

	operations = [
		migrations.AddIndex(
			model_name='revisionchange',
			index=models.Index(
				fields=['target_column', 'target_type'],
				name='revisionchange_column_idx',
			),
		),
		migrations.AddIndex(
			model_name='revisionchange',
			index=django.contrib.postgres.indexes.HashIndex(
				fields=['target_value'], name='revisionchange_value_hash_idx'
			),
		),
		migrations.AddIndex(
			model_name='revisionchangeentity',
			index=models.Index(
				fields=['entity_type', 'entity_id'], name='revisionchangeentity_ent_idx'
			),
		),
	]
