# Generated by Django 6.0.6 on 2026-07-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0118_revisionchange_indexes'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AlterField(
			model_name='moderationevent',
			name='work',
			field=models.ForeignKey(
				blank=True,
				db_constraint=False,
				null=True,
				on_delete=django.db.models.deletion.DO_NOTHING,
				related_name='moderation_events',
				to='otodb.mediawork',
			),
		),
		migrations.AddConstraint(
			model_name='moderationevent',
			constraint=models.CheckConstraint(
				condition=models.Q(
					('work_id__isnull', False),
					('source_id__isnull', False),
					_connector='OR',
				),
				name='moderation_event_has_target',
				violation_error_message='Moderation event must have a target',
			),
		),
	]
