# Generated by Django 6.0.6 on 2026-07-13 14:21

from django.db import migrations, models


def copy_pending_anchor(apps, schema_editor):
	WorkSource = apps.get_model('otodb', 'WorkSource')
	WorkSource.objects.filter(is_pending=True, pending_since__isnull=True).update(
		pending_since=models.F('created_at')
	)


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0119_alter_moderationevent_work_and_more'),
	]

	operations = [
		migrations.AddField(
			model_name='worksource',
			name='pending_since',
			field=models.DateTimeField(blank=True, null=True),
		),
		migrations.RunPython(copy_pending_anchor, migrations.RunPython.noop),
	]
