# Generated by Django 6.0.6 on 2026-09-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0120_worksource_pending_since'),
	]

	operations = [
		migrations.AlterField(
			model_name='profileconnection',
			name='site',
			field=models.IntegerField(
				choices=[
					(0, 'Website'),
					(1, 'Niconico'),
					(2, 'YouTube'),
					(3, 'Bilibili'),
					(4, 'Twitter'),
					(5, 'Bluesky'),
					(6, 'Soundcloud'),
					(7, 'otomad.site'),
				]
			),
		),
		migrations.AlterField(
			model_name='tagworkcreatorconnection',
			name='site',
			field=models.IntegerField(
				choices=[
					(0, 'Website'),
					(1, 'Niconico'),
					(2, 'YouTube'),
					(3, 'Bilibili'),
					(4, 'Twitter'),
					(5, 'Bluesky'),
					(6, 'Soundcloud'),
					(7, 'otomad.site'),
				]
			),
		),
		migrations.AlterField(
			model_name='worksource',
			name='platform',
			field=models.IntegerField(
				choices=[
					(1, 'YouTube'),
					(2, 'Niconico'),
					(3, 'Bilibili'),
					(4, 'SoundCloud'),
					(5, 'Twitter'),
					(6, 'AcFun'),
					(7, 'otomad.site'),
				]
			),
		),
	]
