# Generated by Django 6.0.6 on 2026-07-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0120_worksource_pending_since'),
	]

	operations = [
		migrations.AlterField(
			model_name='userpreference',
			name='setting',
			field=models.IntegerField(
				choices=[
					(1, 'Language'),
					(2, 'Theme'),
					(3, 'Video Platform'),
					(4, 'Prefer Author Upload'),
					(5, 'Graph View Backend'),
				]
			),
		),
	]
