# Generated by Django 6.0.6 on 2026-09-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0120_worksource_pending_since'),
	]

	operations = [
		migrations.AlterField(
			model_name='mediasongconnection',
			name='site',
			field=models.IntegerField(
				choices=[
					(0, 'VGMdb'),
					(1, 'VocaDB'),
					(2, 'Discogs'),
					(3, 'MusicBrainz'),
					(4, 'Rate Your Music'),
					(5, 'dojin-music.info'),
					(6, 'TouhouDB'),
					(20, 'RemyWiki'),
					(21, 'Silent Blue'),
					(22, 'Zenius -I- vanisher.com'),
					(30, 'NND Medley Wiki'),
					(40, 'The Mod Archive'),
					(50, 'Spotify'),
					(51, 'Apple Music'),
					(52, 'YouTube Music'),
					(53, 'Bandcamp'),
					(54, 'SoundCloud'),
				]
			),
		),
	]
