# Generated by Django 6.0.6 on 2026-07-13 19:43

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0121_revision_triggers'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddIndex(
			model_name='subscription',
			index=models.Index(
				fields=['entity_type', 'entity_id'], name='subscription_entity_idx'
			),
		),
		migrations.RemoveIndex(
			model_name='revisionchange',
			name='revisionchange_column_idx',
		),
		migrations.RemoveIndex(
			model_name='revisionchange',
			name='revisionchange_value_hash_idx',
		),
		migrations.AddIndex(
			model_name='revisionchange',
			index=models.Index(
				models.F('target_column'),
				django.db.models.functions.text.MD5('target_value'),
				models.F('target_type'),
				name='revisionchange_col_value_idx',
			),
		),
		migrations.AlterField(
			model_name='revision',
			name='date',
			field=models.DateTimeField(auto_now_add=True, db_index=True),
		),
		migrations.SeparateDatabaseAndState(
			database_operations=[
				migrations.RunSQL(
					sql=(
						'DROP INDEX IF EXISTS "otodb_revisionchangeentity_change_id_2e186a34";'
						'DROP INDEX IF EXISTS "otodb_revisionchangeentity_entity_type_id_9aade9f3";'
					),
					reverse_sql=(
						'CREATE INDEX IF NOT EXISTS "otodb_revisionchangeentity_change_id_2e186a34"'
						' ON "otodb_revisionchangeentity" ("change_id");'
						'CREATE INDEX IF NOT EXISTS "otodb_revisionchangeentity_entity_type_id_9aade9f3"'
						' ON "otodb_revisionchangeentity" ("entity_type_id");'
					),
				),
			],
			state_operations=[
				migrations.AlterField(
					model_name='revisionchangeentity',
					name='change',
					field=models.ForeignKey(
						db_index=False,
						on_delete=django.db.models.deletion.CASCADE,
						to='otodb.revisionchange',
					),
				),
				migrations.AlterField(
					model_name='revisionchangeentity',
					name='entity_type',
					field=models.ForeignKey(
						db_index=False,
						on_delete=django.db.models.deletion.CASCADE,
						to='contenttypes.contenttype',
					),
				),
			],
		),
	]
