# Generated by Django 6.0.6 on 2026-07-13 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('contenttypes', '0002_remove_content_type_name'),
		('otodb', '0121_revision_triggers'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddIndex(
			model_name='subscription',
			index=models.Index(
				fields=['entity_type', 'entity_id'], name='subscription_entity_idx'
			),
		),
	]
