# Generated by Django 6.0.6 on 2026-09-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0122_subscription_subscription_entity_idx'),
	]

	operations = [
		migrations.AlterField(
			model_name='worksource',
			name='platform',
			field=models.IntegerField(
				choices=[
					(1, 'YouTube'),
					(2, 'Niconico'),
					(3, 'Bilibili'),
					(4, 'SoundCloud'),
					(5, 'Twitter'),
					(6, 'AcFun'),
					(7, 'Bluesky'),
				]
			),
		),
	]
