# Generated by Django 6.0.6 on 2026-10-01 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('otodb', '0122_subscription_subscription_entity_idx'),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.AddConstraint(
			model_name='worksource',
			constraint=models.UniqueConstraint(
				fields=('platform', 'source_id'),
				name='unique_worksource_platform_source_id',
				violation_error_message='This source is already registered',
			),
		),
	]
