# Generated by Django 5.1.6 on 2025-02-11 06:05

import tagulous.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otodb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasong',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, case_sensitive=False, force_lowercase=True, help_text='Enter a comma-separated tag string', protect_all=True, related_name='song_tags', to='otodb.tagsong'),
        ),
        migrations.AlterField(
            model_name='mediawork',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, case_sensitive=False, force_lowercase=True, help_text='Enter a comma-separated tag string', protect_all=True, related_name='work_tags', through='otodb.TagWorkInstance', to='otodb.tagwork'),
        ),
    ]
