"""
Django settings for project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.environ.get('OTODB_DEBUG', 'False').lower() == 'true'

if OTODB_BACKEND_SENTRY_DSN := os.environ.get('OTODB_BACKEND_SENTRY_DSN'):
	import sentry_sdk

	sentry_sdk.init(
		dsn=OTODB_BACKEND_SENTRY_DSN,
		send_default_pii=False,  # May need to enable later
		enable_logs=True,
		traces_sample_rate=float(
			os.environ.get('OTODB_BACKEND_SENTRY_TRACES_SAMPLE_RATE', '0.1')
		),
		profiles_sample_rate=float(
			os.environ.get('OTODB_BACKEND_SENTRY_PROFILES_SAMPLE_RATE', '0.1')
		),
		release=os.environ.get('OTODB_HASH', 'unknown'),
	)

if not DEBUG and 'OTODB_SECRET_KEY' not in os.environ:
	logger.critical('No secret key provided (OTODB_SECRET_KEY) -- exiting')
	exit(1)

SECRET_KEY = os.environ.get('OTODB_SECRET_KEY', '1145141919')

COOKIES_FILE = os.environ.get('OTODB_COOKIES_FILE')

EMAIL_USE_TLS = True
EMAIL_HOST = os.environ.get('OTODB_EMAIL_HOST')
EMAIL_PORT = os.environ.get('OTODB_EMAIL_PORT')
EMAIL_HOST_USER = os.environ.get('OTODB_EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('OTODB_EMAIL_HOST_PASSWORD')

ALLOWED_HOSTS = [
	host.strip()
	for host in os.environ.get('OTODB_ALLOWED_HOSTS', '').split(',')
	if host
]
CSRF_TRUSTED_ORIGINS = [
	host.strip()
	for host in os.environ.get('OTODB_CSRF_TRUSTED_ORIGINS', '').split(',')
	if host
]

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'otodb',
	'otodb.account',
	'tagulous',
	'ordered_model',
	'django.contrib.sites',
	'django_comments_xtd',
	'django_comments',
	'rest_framework',
	'corsheaders',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.locale.LocaleMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django_userforeignkey.middleware.UserForeignKeyMiddleware',
	'django_request_cache.middleware.RequestCacheMiddleware',
]

if DEBUG:
	INSTALLED_APPS.append('silk')
	MIDDLEWARE.append('silk.middleware.SilkyMiddleware')

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

if os.environ.get('OTODB_SKIP_DB'):
	DATABASE = {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': ':memory:',
	}
else:
	DATABASE = {
		'ENGINE': 'django.db.backends.postgresql',
		'OPTIONS': {},
	}

	if os.environ.get('OTODB_DB_SERVICE') and os.environ.get('OTODB_DB_PASSFILE'):
		DATABASE['OPTIONS']['service'] = os.environ['OTODB_DB_SERVICE']
		DATABASE['OPTIONS']['passfile'] = os.environ['OTODB_DB_PASSFILE']
	else:
		DATABASE['NAME'] = os.environ['OTODB_DB_NAME']
		DATABASE['USER'] = os.environ['OTODB_DB_USER']
		DATABASE['PASSWORD'] = os.environ['OTODB_DB_PASSWORD']
		DATABASE['HOST'] = os.environ['OTODB_DB_HOST']
		DATABASE['PORT'] = os.environ['OTODB_DB_PORT']
		DATABASE['CONN_MAX_AGE'] = 0
		DATABASE['OPTIONS']['pool'] = {
			'min_size': int(os.environ.get('OTODB_DB_POOL_MIN_SIZE', '4')),
			'max_size': int(os.environ.get('OTODB_DB_POOL_MAX_SIZE', '16')),
			'timeout': int(os.environ.get('OTODB_DB_POOL_TIMEOUT', '10')),
			'max_lifetime': int(os.environ.get('OTODB_DB_POOL_MAX_LIFETIME', '1800')),
			'max_idle': int(os.environ.get('OTODB_DB_POOL_MAX_IDLE', '300')),
		}

DATABASES = {
	'default': DATABASE,
}

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

AUTH_USER_MODEL = 'account.Account'

STORAGES = {
	'default': {
		'BACKEND': 'django.core.files.storage.FileSystemStorage',
	},
	'staticfiles': {
		'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
	},
}

STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
	ip.strip() for ip in os.environ.get('OTODB_INTERNAL_IPS', '').split(',') if ip
]

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login'

OTODB_CONFIG_DICT = {'site_name': os.environ.get('OTODB_CONF_SITE_NAME', 'otoDB')}

SERIALIZATION_MODULES = {
	'xml': 'tagulous.serializers.xml_serializer',
	'json': 'tagulous.serializers.json',
	'python': 'tagulous.serializers.python',
	'yaml': 'tagulous.serializers.pyyaml',
}

TAGULOUS_SLUG_ALLOW_UNICODE = True

SITE_ID = 1
COMMENTS_APP = 'django_comments_xtd'
COMMENTS_XTD_MAX_THREAD_LEVEL = 3

COMMENTS_XTD_APP_MODEL_OPTIONS = {
	'default': {
		'allow_flagging': True,
		'allow_feedback': False,
		'show_feedback': False,
		'who_can_post': 'users',
	}
}

CORS_ALLOW_CREDENTIALS = True
if DEBUG:
	CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
	'https://cdn.jsdelivr.net',
	'https://unpkg.com',
	'https://www.youtube.com',
	'https://www.nicovideo.jp',
	'https://www.bilibili.com',
]

OTODB_FRONTEND_DOMAIN = os.environ.get('OTODB_FRONTEND_DOMAIN')
if OTODB_FRONTEND_DOMAIN:
	CORS_ALLOWED_ORIGINS.append('https://' + OTODB_FRONTEND_DOMAIN)
	CORS_ALLOWED_ORIGINS.append('http://' + OTODB_FRONTEND_DOMAIN)
	CSRF_TRUSTED_ORIGINS = [
		'http://' + OTODB_FRONTEND_DOMAIN,
		'https://' + OTODB_FRONTEND_DOMAIN,
	]

OTODB_PROTECT_API_DOCS = os.environ.get('OTODB_PROTECT_API_DOCS', '').lower() == 'true'

INTERNAL_API_SECRET = os.environ.get('INTERNAL_API_SECRET')

# CDN Configuration
OTODB_CDN_BUCKET_NAME = os.environ.get('OTODB_CDN_BUCKET_NAME')
OTODB_CDN_ENDPOINT_URL = os.environ.get('OTODB_CDN_ENDPOINT_URL')
OTODB_CDN_ACCESS_KEY = os.environ.get('OTODB_CDN_ACCESS_KEY')
OTODB_CDN_SECRET_KEY = os.environ.get('OTODB_CDN_SECRET_KEY')
OTODB_CDN_HOST = os.environ.get('OTODB_CDN_HOST')
OTODB_CDN_ENABLED = (
	all(
		[
			OTODB_CDN_BUCKET_NAME,
			OTODB_CDN_ENDPOINT_URL,
			OTODB_CDN_ACCESS_KEY,
			OTODB_CDN_SECRET_KEY,
			OTODB_CDN_HOST,
		]
	)
	if os.environ.get('OTODB_CDN_ENABLED', '').lower() not in ('0', 'false')
	else False
)
OTODB_CDN_ROOT = os.environ.get('OTODB_CDN_ROOT', '/')

# Task queue (Redis + RQ in production, synchronous fallback for dev)
OTODB_REDIS_URL = os.environ.get('OTODB_REDIS_URL')
if OTODB_REDIS_URL:
	INSTALLED_APPS.append('django_rq')
	RQ_QUEUES = {
		'default': {
			'URL': OTODB_REDIS_URL,
		}
	}
	TASKS = {
		'default': {
			'BACKEND': 'django_tasks_rq.RQBackend',
			'QUEUES': ['default'],
		}
	}
	CACHES = {
		'default': {
			'BACKEND': 'django.core.cache.backends.redis.RedisCache',
			'LOCATION': OTODB_REDIS_URL,
		}
	}
else:
	TASKS = {
		'default': {
			'BACKEND': 'django.tasks.backends.immediate.ImmediateBackend',
		}
	}

OTODB_DISCORD_WEBHOOK_URL = os.environ.get('OTODB_DISCORD_WEBHOOK_URL')

NINJA_PAGINATION_PER_PAGE = 30
NINJA_PAGINATION_MAX_PER_PAGE_SIZE = 30
NINJA_PAGINATION_MAX_LIMIT = 30

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'handlers': {
		'console': {
			'class': 'logging.StreamHandler',
		},
	},
	'root': {
		'handlers': ['console'],
		'level': 'INFO',
	},
}

# Application specific

# TODO: Consider making these dynamic per user rather than a fixed number
OTODB_MAX_PENDING_WORKS = 10
OTODB_MAX_FLAGGED_WORKS = 5

OTODB_COMMENT_EDIT_WINDOW = timedelta(days=180)
OTODB_MODERATION_PERIOD = timedelta(weeks=1)
