# Generated by Django 6.0.4 on 2026-05-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('account', '0008_create_system_bot_account'),
	]

	operations = [
		migrations.AlterField(
			model_name='account',
			name='level',
			field=models.IntegerField(
				choices=[
					(0, 'Anonymous'),
					(10, 'Restricted'),
					(20, 'Member'),
					(40, 'Editor'),
					(50, 'Mod'),
					(100, 'Admin'),
				],
				default=20,
			),
		),
		migrations.AlterField(
			model_name='invitation',
			name='level',
			field=models.IntegerField(
				choices=[
					(0, 'Anonymous'),
					(10, 'Restricted'),
					(20, 'Member'),
					(40, 'Editor'),
					(50, 'Mod'),
					(100, 'Admin'),
				]
			),
		),
	]
