-- ===========================================================================
-- GENERATED by otodb/revision_codegen.py from otodb/revision_spec.py -- DO NOT EDIT.
-- Regenerate: python -m otodb.revision_codegen > otodb/sql/revision_triggers.sql
-- ===========================================================================

-- Content-type id for an app_label/model (STABLE: planner caches within a statement).
CREATE OR REPLACE FUNCTION otodb_ct(p_app text, p_model text)
RETURNS integer LANGUAGE sql STABLE AS $$
	SELECT id FROM django_content_type WHERE app_label = p_app AND model = p_model;
$$;

-- One Revision per transaction, created LAZILY on the first real change; its id is
-- parked in a txn-local setting so later changes in the same txn attach to it.
-- Attribution: an absent/empty otodb.user_id (unstamped writes -- scheduler jobs like
-- prune_expired, raw SQL, data migrations) falls back to the system bot: account id 1,
-- the first account, created by account migration 0008 on a fresh schema.
CREATE OR REPLACE FUNCTION otodb_current_revision()
RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE
	rid bigint;
	uid text;
BEGIN
	rid := nullif(current_setting('otodb.rev_id', true), '')::bigint;
	IF rid IS NOT NULL THEN
		RETURN rid;
	END IF;
	uid := nullif(current_setting('otodb.user_id', true), '');
	INSERT INTO otodb_revision (user_id, "date", message)
	VALUES (
		coalesce(uid::bigint, 1),
		now(),
		coalesce(nullif(current_setting('otodb.message', true), ''), '')
	)
	RETURNING id INTO rid;
	PERFORM set_config('otodb.rev_id', rid::text, true);
	RETURN rid;
END;
$$;

-- Emit one RevisionChangeEntity row (skips NULL entity ids; idempotent).
CREATE OR REPLACE FUNCTION otodb_emit_entity(
	p_change bigint, p_entity_ct integer, p_entity_id bigint, p_route integer
)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
	IF p_entity_id IS NULL THEN
		RETURN;
	END IF;
	INSERT INTO otodb_revisionchangeentity (change_id, entity_type_id, entity_id, route)
	VALUES (p_change, p_entity_ct, p_entity_id, p_route)
	ON CONFLICT (change_id, entity_type_id, entity_id) DO NOTHING;
END;
$$;

-- Side effects of a completed Revision, invoked by the writer in the same transaction:
-- SELECT otodb_fan_out(rev_id). Notifies subscribers of the changed rows, auto-
-- subscribes the (active) actor to the routed entities, then drops subscriptions whose
-- row was deleted (the generic FK cannot cascade). Subscriptions persist across changes
-- (a subscriber is notified of every revision touching the row); pruning runs LAST so a
-- subscription to a row deleted in this revision -- pre-existing or just auto-created --
-- never outlives it. IS DISTINCT FROM excludes the actor while still notifying everyone
-- on an anonymous (NULL-user) edit.
CREATE OR REPLACE FUNCTION otodb_fan_out(p_rev bigint)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
	WITH touched AS (
		SELECT DISTINCT target_type_id AS et, target_id AS eid
		FROM otodb_revisionchange WHERE rev_id = p_rev
	)
	INSERT INTO otodb_notification (target_id, revision_id, reason, dismissed, created_at)
	SELECT DISTINCT s.subscriber_id, p_rev, 0, false, now()
	FROM otodb_subscription s
	JOIN touched t ON s.entity_type_id = t.et AND s.entity_id = t.eid
	JOIN otodb_revision r ON r.id = p_rev
	WHERE s.subscriber_id IS DISTINCT FROM r.user_id;

	INSERT INTO otodb_subscription (subscriber_id, entity_type_id, entity_id)
	SELECT r.user_id, rce.entity_type_id, rce.entity_id
	FROM otodb_revision r
	JOIN otodb_revisionchange rc ON rc.rev_id = r.id
	JOIN otodb_revisionchangeentity rce ON rce.change_id = rc.id
	JOIN account_account a ON a.id = r.user_id AND a.is_active
	WHERE r.id = p_rev
	ON CONFLICT (subscriber_id, entity_type_id, entity_id) DO NOTHING;

	DELETE FROM otodb_subscription s
	USING otodb_revisionchange rc
	WHERE rc.rev_id = p_rev AND rc.deleted
		AND s.entity_type_id = rc.target_type_id
		AND s.entity_id = rc.target_id;
END;
$$;


-- mediasong: tracked=['title', 'bpm', 'variable_bpm', 'work_tag', 'author']
CREATE OR REPLACE FUNCTION otodb_mediasong_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'mediasong');
	cid bigint;
	ct_tagwork integer := otodb_ct('otodb', 'tagwork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, own_ct, OLD."id", route);
			PERFORM otodb_emit_entity(cid, ct_tagwork, OLD."work_tag_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."title" IS DISTINCT FROM OLD."title" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'title', NEW."title", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."work_tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."bpm" IS DISTINCT FROM OLD."bpm" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'bpm', CASE WHEN NEW."bpm" IS NULL THEN NULL WHEN NEW."bpm" = trunc(NEW."bpm") AND abs(NEW."bpm") < 1e16 THEN NEW."bpm"::text || '.0' ELSE NEW."bpm"::text END, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."work_tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."variable_bpm" IS DISTINCT FROM OLD."variable_bpm" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'variable_bpm', CASE WHEN NEW."variable_bpm" IS NULL THEN NULL WHEN NEW."variable_bpm" THEN 'True' ELSE 'False' END, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."work_tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."work_tag_id" IS DISTINCT FROM OLD."work_tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'work_tag', NEW."work_tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."work_tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."author" IS DISTINCT FROM OLD."author" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'author', NEW."author", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."work_tag_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_mediasong_capture ON otodb_mediasong;
CREATE OR REPLACE TRIGGER zz_otodb_mediasong_capture_i
AFTER INSERT ON otodb_mediasong
FOR EACH ROW EXECUTE FUNCTION otodb_mediasong_capture();
CREATE OR REPLACE TRIGGER zz_otodb_mediasong_capture_u
AFTER UPDATE ON otodb_mediasong
FOR EACH ROW WHEN (OLD."title" IS DISTINCT FROM NEW."title"
	 OR OLD."bpm" IS DISTINCT FROM NEW."bpm"
	 OR OLD."variable_bpm" IS DISTINCT FROM NEW."variable_bpm"
	 OR OLD."work_tag_id" IS DISTINCT FROM NEW."work_tag_id"
	 OR OLD."author" IS DISTINCT FROM NEW."author")
EXECUTE FUNCTION otodb_mediasong_capture();
CREATE OR REPLACE TRIGGER zz_otodb_mediasong_capture_d
AFTER DELETE ON otodb_mediasong
FOR EACH ROW EXECUTE FUNCTION otodb_mediasong_capture();

-- mediasongconnection: tracked=['song', 'site', 'content_id']
CREATE OR REPLACE FUNCTION otodb_mediasongconnection_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'mediasongconnection');
	cid bigint;
	ct_mediasong integer := otodb_ct('otodb', 'mediasong');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_mediasong, OLD."song_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."song_id" IS DISTINCT FROM OLD."song_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'song', NEW."song_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."song_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."site" IS DISTINCT FROM OLD."site" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'site', NEW."site"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."song_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."content_id" IS DISTINCT FROM OLD."content_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'content_id', NEW."content_id", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."song_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_mediasongconnection_capture ON otodb_mediasongconnection;
CREATE OR REPLACE TRIGGER zz_otodb_mediasongconnection_capture_i
AFTER INSERT ON otodb_mediasongconnection
FOR EACH ROW EXECUTE FUNCTION otodb_mediasongconnection_capture();
CREATE OR REPLACE TRIGGER zz_otodb_mediasongconnection_capture_u
AFTER UPDATE ON otodb_mediasongconnection
FOR EACH ROW WHEN (OLD."song_id" IS DISTINCT FROM NEW."song_id"
	 OR OLD."site" IS DISTINCT FROM NEW."site"
	 OR OLD."content_id" IS DISTINCT FROM NEW."content_id")
EXECUTE FUNCTION otodb_mediasongconnection_capture();
CREATE OR REPLACE TRIGGER zz_otodb_mediasongconnection_capture_d
AFTER DELETE ON otodb_mediasongconnection
FOR EACH ROW EXECUTE FUNCTION otodb_mediasongconnection_capture();

-- mediawork: tracked=['title', 'description', 'rating', 'moved_to']
CREATE OR REPLACE FUNCTION otodb_mediawork_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'mediawork');
	cid bigint;
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, own_ct, OLD."id", route);
			PERFORM otodb_emit_entity(cid, own_ct, OLD."moved_to_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."title" IS DISTINCT FROM OLD."title" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'title', NEW."title", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."moved_to_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."description" IS DISTINCT FROM OLD."description" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'description', NEW."description", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."moved_to_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."rating" IS DISTINCT FROM OLD."rating" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'rating', NEW."rating"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."moved_to_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."moved_to_id" IS DISTINCT FROM OLD."moved_to_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'moved_to', NEW."moved_to_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."moved_to_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_mediawork_capture ON otodb_mediawork;
CREATE OR REPLACE TRIGGER zz_otodb_mediawork_capture_i
AFTER INSERT ON otodb_mediawork
FOR EACH ROW EXECUTE FUNCTION otodb_mediawork_capture();
CREATE OR REPLACE TRIGGER zz_otodb_mediawork_capture_u
AFTER UPDATE ON otodb_mediawork
FOR EACH ROW WHEN (OLD."title" IS DISTINCT FROM NEW."title"
	 OR OLD."description" IS DISTINCT FROM NEW."description"
	 OR OLD."rating" IS DISTINCT FROM NEW."rating"
	 OR OLD."moved_to_id" IS DISTINCT FROM NEW."moved_to_id")
EXECUTE FUNCTION otodb_mediawork_capture();
CREATE OR REPLACE TRIGGER zz_otodb_mediawork_capture_d
AFTER DELETE ON otodb_mediawork
FOR EACH ROW EXECUTE FUNCTION otodb_mediawork_capture();

-- songrelation: tracked=['A', 'B', 'relation']
CREATE OR REPLACE FUNCTION otodb_songrelation_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'songrelation');
	cid bigint;
	ct_mediasong integer := otodb_ct('otodb', 'mediasong');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_mediasong, OLD."A_id", route);
			PERFORM otodb_emit_entity(cid, ct_mediasong, OLD."B_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."A_id" IS DISTINCT FROM OLD."A_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'A', NEW."A_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."A_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."B_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."B_id" IS DISTINCT FROM OLD."B_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'B', NEW."B_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."A_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."B_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."relation" IS DISTINCT FROM OLD."relation" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'relation', NEW."relation"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."A_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."B_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_songrelation_capture ON otodb_songrelation;
CREATE OR REPLACE TRIGGER zz_otodb_songrelation_capture_i
AFTER INSERT ON otodb_songrelation
FOR EACH ROW EXECUTE FUNCTION otodb_songrelation_capture();
CREATE OR REPLACE TRIGGER zz_otodb_songrelation_capture_u
AFTER UPDATE ON otodb_songrelation
FOR EACH ROW WHEN (OLD."A_id" IS DISTINCT FROM NEW."A_id"
	 OR OLD."B_id" IS DISTINCT FROM NEW."B_id"
	 OR OLD."relation" IS DISTINCT FROM NEW."relation")
EXECUTE FUNCTION otodb_songrelation_capture();
CREATE OR REPLACE TRIGGER zz_otodb_songrelation_capture_d
AFTER DELETE ON otodb_songrelation
FOR EACH ROW EXECUTE FUNCTION otodb_songrelation_capture();

-- tagsong: tracked=['name', 'slug', 'aliased_to', 'category', 'parent']
CREATE OR REPLACE FUNCTION otodb_tagsong_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagsong');
	cid bigint;
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, own_ct, OLD."id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."name" IS DISTINCT FROM OLD."name" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'name', NEW."name", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."slug" IS DISTINCT FROM OLD."slug" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'slug', NEW."slug", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."aliased_to_id" IS DISTINCT FROM OLD."aliased_to_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'aliased_to', NEW."aliased_to_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."category" IS DISTINCT FROM OLD."category" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'category', NEW."category"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."parent_id" IS DISTINCT FROM OLD."parent_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'parent', NEW."parent_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagsong_capture ON otodb_tagsong;
CREATE OR REPLACE TRIGGER zz_otodb_tagsong_capture_i
AFTER INSERT ON otodb_tagsong
FOR EACH ROW EXECUTE FUNCTION otodb_tagsong_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagsong_capture_u
AFTER UPDATE ON otodb_tagsong
FOR EACH ROW WHEN (OLD."name" IS DISTINCT FROM NEW."name"
	 OR OLD."slug" IS DISTINCT FROM NEW."slug"
	 OR OLD."aliased_to_id" IS DISTINCT FROM NEW."aliased_to_id"
	 OR OLD."category" IS DISTINCT FROM NEW."category"
	 OR OLD."parent_id" IS DISTINCT FROM NEW."parent_id")
EXECUTE FUNCTION otodb_tagsong_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagsong_capture_d
AFTER DELETE ON otodb_tagsong
FOR EACH ROW EXECUTE FUNCTION otodb_tagsong_capture();

-- tagsonginstance: tracked=['song', 'song_tag']
CREATE OR REPLACE FUNCTION otodb_tagsonginstance_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagsonginstance');
	cid bigint;
	ct_mediasong integer := otodb_ct('otodb', 'mediasong');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_mediasong, OLD."song_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."song_id" IS DISTINCT FROM OLD."song_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'song', NEW."song_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."song_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."song_tag_id" IS DISTINCT FROM OLD."song_tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'song_tag', NEW."song_tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediasong, NEW."song_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagsonginstance_capture ON otodb_tagsonginstance;
CREATE OR REPLACE TRIGGER zz_otodb_tagsonginstance_capture_i
AFTER INSERT ON otodb_tagsonginstance
FOR EACH ROW EXECUTE FUNCTION otodb_tagsonginstance_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagsonginstance_capture_u
AFTER UPDATE ON otodb_tagsonginstance
FOR EACH ROW WHEN (OLD."song_id" IS DISTINCT FROM NEW."song_id"
	 OR OLD."song_tag_id" IS DISTINCT FROM NEW."song_tag_id")
EXECUTE FUNCTION otodb_tagsonginstance_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagsonginstance_capture_d
AFTER DELETE ON otodb_tagsonginstance
FOR EACH ROW EXECUTE FUNCTION otodb_tagsonginstance_capture();

-- tagsonglangpreference: tracked=['lang', 'tag']
CREATE OR REPLACE FUNCTION otodb_tagsonglangpreference_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagsonglangpreference');
	cid bigint;
	ct_tagsong integer := otodb_ct('otodb', 'tagsong');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_tagsong, OLD."tag_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."lang" IS DISTINCT FROM OLD."lang" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'lang', NEW."lang"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagsong, NEW."tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."tag_id" IS DISTINCT FROM OLD."tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'tag', NEW."tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagsong, NEW."tag_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagsonglangpreference_capture ON otodb_tagsonglangpreference;
CREATE OR REPLACE TRIGGER zz_otodb_tagsonglangpreference_capture_i
AFTER INSERT ON otodb_tagsonglangpreference
FOR EACH ROW EXECUTE FUNCTION otodb_tagsonglangpreference_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagsonglangpreference_capture_u
AFTER UPDATE ON otodb_tagsonglangpreference
FOR EACH ROW WHEN (OLD."lang" IS DISTINCT FROM NEW."lang"
	 OR OLD."tag_id" IS DISTINCT FROM NEW."tag_id")
EXECUTE FUNCTION otodb_tagsonglangpreference_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagsonglangpreference_capture_d
AFTER DELETE ON otodb_tagsonglangpreference
FOR EACH ROW EXECUTE FUNCTION otodb_tagsonglangpreference_capture();

-- tagwork: tracked=['name', 'slug', 'aliased_to', 'deprecated', 'category', 'media_type']
CREATE OR REPLACE FUNCTION otodb_tagwork_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagwork');
	cid bigint;
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, own_ct, OLD."id", route);
			PERFORM otodb_emit_entity(cid, own_ct, OLD."aliased_to_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."name" IS DISTINCT FROM OLD."name" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'name', NEW."name", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."aliased_to_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."slug" IS DISTINCT FROM OLD."slug" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'slug', NEW."slug", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."aliased_to_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."aliased_to_id" IS DISTINCT FROM OLD."aliased_to_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'aliased_to', NEW."aliased_to_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."aliased_to_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."deprecated" IS DISTINCT FROM OLD."deprecated" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'deprecated', CASE WHEN NEW."deprecated" IS NULL THEN NULL WHEN NEW."deprecated" THEN 'True' ELSE 'False' END, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."aliased_to_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."category" IS DISTINCT FROM OLD."category" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'category', NEW."category"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."aliased_to_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."media_type" IS DISTINCT FROM OLD."media_type" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'media_type', NEW."media_type"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, own_ct, NEW."aliased_to_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagwork_capture ON otodb_tagwork;
CREATE OR REPLACE TRIGGER zz_otodb_tagwork_capture_i
AFTER INSERT ON otodb_tagwork
FOR EACH ROW EXECUTE FUNCTION otodb_tagwork_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagwork_capture_u
AFTER UPDATE ON otodb_tagwork
FOR EACH ROW WHEN (OLD."name" IS DISTINCT FROM NEW."name"
	 OR OLD."slug" IS DISTINCT FROM NEW."slug"
	 OR OLD."aliased_to_id" IS DISTINCT FROM NEW."aliased_to_id"
	 OR OLD."deprecated" IS DISTINCT FROM NEW."deprecated"
	 OR OLD."category" IS DISTINCT FROM NEW."category"
	 OR OLD."media_type" IS DISTINCT FROM NEW."media_type")
EXECUTE FUNCTION otodb_tagwork_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagwork_capture_d
AFTER DELETE ON otodb_tagwork
FOR EACH ROW EXECUTE FUNCTION otodb_tagwork_capture();

-- tagworkconnection: tracked=['tag', 'site', 'content_id']
CREATE OR REPLACE FUNCTION otodb_tagworkconnection_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagworkconnection');
	cid bigint;
	ct_tagwork integer := otodb_ct('otodb', 'tagwork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_tagwork, OLD."tag_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."tag_id" IS DISTINCT FROM OLD."tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'tag', NEW."tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."site" IS DISTINCT FROM OLD."site" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'site', NEW."site"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."content_id" IS DISTINCT FROM OLD."content_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'content_id', NEW."content_id", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagworkconnection_capture ON otodb_tagworkconnection;
CREATE OR REPLACE TRIGGER zz_otodb_tagworkconnection_capture_i
AFTER INSERT ON otodb_tagworkconnection
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkconnection_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkconnection_capture_u
AFTER UPDATE ON otodb_tagworkconnection
FOR EACH ROW WHEN (OLD."tag_id" IS DISTINCT FROM NEW."tag_id"
	 OR OLD."site" IS DISTINCT FROM NEW."site"
	 OR OLD."content_id" IS DISTINCT FROM NEW."content_id")
EXECUTE FUNCTION otodb_tagworkconnection_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkconnection_capture_d
AFTER DELETE ON otodb_tagworkconnection
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkconnection_capture();

-- tagworkcreatorconnection: tracked=['tag', 'site', 'content_id', 'dead']
CREATE OR REPLACE FUNCTION otodb_tagworkcreatorconnection_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagworkcreatorconnection');
	cid bigint;
	ct_tagwork integer := otodb_ct('otodb', 'tagwork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_tagwork, OLD."tag_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."tag_id" IS DISTINCT FROM OLD."tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'tag', NEW."tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."site" IS DISTINCT FROM OLD."site" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'site', NEW."site"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."content_id" IS DISTINCT FROM OLD."content_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'content_id', NEW."content_id", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."dead" IS DISTINCT FROM OLD."dead" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'dead', CASE WHEN NEW."dead" IS NULL THEN NULL WHEN NEW."dead" THEN 'True' ELSE 'False' END, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagworkcreatorconnection_capture ON otodb_tagworkcreatorconnection;
CREATE OR REPLACE TRIGGER zz_otodb_tagworkcreatorconnection_capture_i
AFTER INSERT ON otodb_tagworkcreatorconnection
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkcreatorconnection_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkcreatorconnection_capture_u
AFTER UPDATE ON otodb_tagworkcreatorconnection
FOR EACH ROW WHEN (OLD."tag_id" IS DISTINCT FROM NEW."tag_id"
	 OR OLD."site" IS DISTINCT FROM NEW."site"
	 OR OLD."content_id" IS DISTINCT FROM NEW."content_id"
	 OR OLD."dead" IS DISTINCT FROM NEW."dead")
EXECUTE FUNCTION otodb_tagworkcreatorconnection_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkcreatorconnection_capture_d
AFTER DELETE ON otodb_tagworkcreatorconnection
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkcreatorconnection_capture();

-- tagworkinstance: tracked=['work', 'work_tag', 'used_as_source', 'creator_roles']
CREATE OR REPLACE FUNCTION otodb_tagworkinstance_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagworkinstance');
	cid bigint;
	ct_mediawork integer := otodb_ct('otodb', 'mediawork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_mediawork, OLD."work_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."work_id" IS DISTINCT FROM OLD."work_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'work', NEW."work_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."work_tag_id" IS DISTINCT FROM OLD."work_tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'work_tag', NEW."work_tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."used_as_source" IS DISTINCT FROM OLD."used_as_source" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'used_as_source', CASE WHEN NEW."used_as_source" IS NULL THEN NULL WHEN NEW."used_as_source" THEN 'True' ELSE 'False' END, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."creator_roles" IS DISTINCT FROM OLD."creator_roles" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'creator_roles', NEW."creator_roles"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagworkinstance_capture ON otodb_tagworkinstance;
CREATE OR REPLACE TRIGGER zz_otodb_tagworkinstance_capture_i
AFTER INSERT ON otodb_tagworkinstance
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkinstance_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkinstance_capture_u
AFTER UPDATE ON otodb_tagworkinstance
FOR EACH ROW WHEN (OLD."work_id" IS DISTINCT FROM NEW."work_id"
	 OR OLD."work_tag_id" IS DISTINCT FROM NEW."work_tag_id"
	 OR OLD."used_as_source" IS DISTINCT FROM NEW."used_as_source"
	 OR OLD."creator_roles" IS DISTINCT FROM NEW."creator_roles")
EXECUTE FUNCTION otodb_tagworkinstance_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkinstance_capture_d
AFTER DELETE ON otodb_tagworkinstance
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkinstance_capture();

-- tagworklangpreference: tracked=['lang', 'tag']
CREATE OR REPLACE FUNCTION otodb_tagworklangpreference_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagworklangpreference');
	cid bigint;
	ct_tagwork integer := otodb_ct('otodb', 'tagwork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_tagwork, OLD."tag_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."lang" IS DISTINCT FROM OLD."lang" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'lang', NEW."lang"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."tag_id" IS DISTINCT FROM OLD."tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'tag', NEW."tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagworklangpreference_capture ON otodb_tagworklangpreference;
CREATE OR REPLACE TRIGGER zz_otodb_tagworklangpreference_capture_i
AFTER INSERT ON otodb_tagworklangpreference
FOR EACH ROW EXECUTE FUNCTION otodb_tagworklangpreference_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworklangpreference_capture_u
AFTER UPDATE ON otodb_tagworklangpreference
FOR EACH ROW WHEN (OLD."lang" IS DISTINCT FROM NEW."lang"
	 OR OLD."tag_id" IS DISTINCT FROM NEW."tag_id")
EXECUTE FUNCTION otodb_tagworklangpreference_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworklangpreference_capture_d
AFTER DELETE ON otodb_tagworklangpreference
FOR EACH ROW EXECUTE FUNCTION otodb_tagworklangpreference_capture();

-- tagworkmediaconnection: tracked=['tag', 'site', 'content_id']
CREATE OR REPLACE FUNCTION otodb_tagworkmediaconnection_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagworkmediaconnection');
	cid bigint;
	ct_tagwork integer := otodb_ct('otodb', 'tagwork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_tagwork, OLD."tag_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."tag_id" IS DISTINCT FROM OLD."tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'tag', NEW."tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."site" IS DISTINCT FROM OLD."site" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'site', NEW."site"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."content_id" IS DISTINCT FROM OLD."content_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'content_id', NEW."content_id", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagworkmediaconnection_capture ON otodb_tagworkmediaconnection;
CREATE OR REPLACE TRIGGER zz_otodb_tagworkmediaconnection_capture_i
AFTER INSERT ON otodb_tagworkmediaconnection
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkmediaconnection_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkmediaconnection_capture_u
AFTER UPDATE ON otodb_tagworkmediaconnection
FOR EACH ROW WHEN (OLD."tag_id" IS DISTINCT FROM NEW."tag_id"
	 OR OLD."site" IS DISTINCT FROM NEW."site"
	 OR OLD."content_id" IS DISTINCT FROM NEW."content_id")
EXECUTE FUNCTION otodb_tagworkmediaconnection_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkmediaconnection_capture_d
AFTER DELETE ON otodb_tagworkmediaconnection
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkmediaconnection_capture();

-- tagworkparenthood: tracked=['tag', 'parent', 'primary']
CREATE OR REPLACE FUNCTION otodb_tagworkparenthood_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'tagworkparenthood');
	cid bigint;
	ct_tagwork integer := otodb_ct('otodb', 'tagwork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_tagwork, OLD."tag_id", route);
			PERFORM otodb_emit_entity(cid, ct_tagwork, OLD."parent_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."tag_id" IS DISTINCT FROM OLD."tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'tag', NEW."tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."parent_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."parent_id" IS DISTINCT FROM OLD."parent_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'parent', NEW."parent_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."parent_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."primary" IS DISTINCT FROM OLD."primary" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'primary', CASE WHEN NEW."primary" IS NULL THEN NULL WHEN NEW."primary" THEN 'True' ELSE 'False' END, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."parent_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_tagworkparenthood_capture ON otodb_tagworkparenthood;
CREATE OR REPLACE TRIGGER zz_otodb_tagworkparenthood_capture_i
AFTER INSERT ON otodb_tagworkparenthood
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkparenthood_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkparenthood_capture_u
AFTER UPDATE ON otodb_tagworkparenthood
FOR EACH ROW WHEN (OLD."tag_id" IS DISTINCT FROM NEW."tag_id"
	 OR OLD."parent_id" IS DISTINCT FROM NEW."parent_id"
	 OR OLD."primary" IS DISTINCT FROM NEW."primary")
EXECUTE FUNCTION otodb_tagworkparenthood_capture();
CREATE OR REPLACE TRIGGER zz_otodb_tagworkparenthood_capture_d
AFTER DELETE ON otodb_tagworkparenthood
FOR EACH ROW EXECUTE FUNCTION otodb_tagworkparenthood_capture();

-- wikipage: tracked=['lang', 'tag', 'work', 'slug', 'title', 'page']
CREATE OR REPLACE FUNCTION otodb_wikipage_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'wikipage');
	cid bigint;
	ct_tagwork integer := otodb_ct('otodb', 'tagwork');
	ct_mediawork integer := otodb_ct('otodb', 'mediawork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, own_ct, OLD."id", route);
			PERFORM otodb_emit_entity(cid, ct_tagwork, OLD."tag_id", route);
			PERFORM otodb_emit_entity(cid, ct_mediawork, OLD."work_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."lang" IS DISTINCT FROM OLD."lang" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'lang', NEW."lang"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."tag_id" IS DISTINCT FROM OLD."tag_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'tag', NEW."tag_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."work_id" IS DISTINCT FROM OLD."work_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'work', NEW."work_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."slug" IS DISTINCT FROM OLD."slug" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'slug', NEW."slug", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."title" IS DISTINCT FROM OLD."title" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'title', NEW."title", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."page" IS DISTINCT FROM OLD."page" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'page', NEW."page", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_tagwork, NEW."tag_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."work_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_wikipage_capture ON otodb_wikipage;
CREATE OR REPLACE TRIGGER zz_otodb_wikipage_capture_i
AFTER INSERT ON otodb_wikipage
FOR EACH ROW EXECUTE FUNCTION otodb_wikipage_capture();
CREATE OR REPLACE TRIGGER zz_otodb_wikipage_capture_u
AFTER UPDATE ON otodb_wikipage
FOR EACH ROW WHEN (OLD."lang" IS DISTINCT FROM NEW."lang"
	 OR OLD."tag_id" IS DISTINCT FROM NEW."tag_id"
	 OR OLD."work_id" IS DISTINCT FROM NEW."work_id"
	 OR OLD."slug" IS DISTINCT FROM NEW."slug"
	 OR OLD."title" IS DISTINCT FROM NEW."title"
	 OR OLD."page" IS DISTINCT FROM NEW."page")
EXECUTE FUNCTION otodb_wikipage_capture();
CREATE OR REPLACE TRIGGER zz_otodb_wikipage_capture_d
AFTER DELETE ON otodb_wikipage
FOR EACH ROW EXECUTE FUNCTION otodb_wikipage_capture();

-- workrelation: tracked=['A', 'B', 'relation']
CREATE OR REPLACE FUNCTION otodb_workrelation_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'workrelation');
	cid bigint;
	ct_mediawork integer := otodb_ct('otodb', 'mediawork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, ct_mediawork, OLD."A_id", route);
			PERFORM otodb_emit_entity(cid, ct_mediawork, OLD."B_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."A_id" IS DISTINCT FROM OLD."A_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'A', NEW."A_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."A_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."B_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."B_id" IS DISTINCT FROM OLD."B_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'B', NEW."B_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."A_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."B_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."relation" IS DISTINCT FROM OLD."relation" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'relation', NEW."relation"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."A_id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."B_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_workrelation_capture ON otodb_workrelation;
CREATE OR REPLACE TRIGGER zz_otodb_workrelation_capture_i
AFTER INSERT ON otodb_workrelation
FOR EACH ROW EXECUTE FUNCTION otodb_workrelation_capture();
CREATE OR REPLACE TRIGGER zz_otodb_workrelation_capture_u
AFTER UPDATE ON otodb_workrelation
FOR EACH ROW WHEN (OLD."A_id" IS DISTINCT FROM NEW."A_id"
	 OR OLD."B_id" IS DISTINCT FROM NEW."B_id"
	 OR OLD."relation" IS DISTINCT FROM NEW."relation")
EXECUTE FUNCTION otodb_workrelation_capture();
CREATE OR REPLACE TRIGGER zz_otodb_workrelation_capture_d
AFTER DELETE ON otodb_workrelation
FOR EACH ROW EXECUTE FUNCTION otodb_workrelation_capture();

-- worksource: tracked=['media', 'platform', 'source_id', 'url', 'published_date', 'work_origin', 'work_status', 'work_width', 'work_height', 'work_duration', 'title', 'description', 'thumbnail_url', 'thumbnail_mime', 'thumbnail_hash', 'uploader_id', 'added_by']
CREATE OR REPLACE FUNCTION otodb_worksource_capture() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
	rev bigint;
	tid bigint := coalesce(NEW."id", OLD."id");
	route integer := coalesce(nullif(current_setting('otodb.route', true), '')::int, 0);
	own_ct integer := otodb_ct('otodb', 'worksource');
	cid bigint;
	ct_mediawork integer := otodb_ct('otodb', 'mediawork');
BEGIN
	IF TG_OP = 'DELETE' THEN
		rev := otodb_current_revision();
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, OLD."id", NULL, NULL, true, false)
		ON CONFLICT (target_type_id, target_id) WHERE deleted DO NOTHING
		RETURNING id INTO cid;
		IF cid IS NOT NULL THEN
			PERFORM otodb_emit_entity(cid, own_ct, OLD."id", route);
			PERFORM otodb_emit_entity(cid, ct_mediawork, OLD."media_id", route);
		END IF;
		RETURN OLD;
	END IF;

	IF TG_OP = 'INSERT' OR NEW."media_id" IS DISTINCT FROM OLD."media_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'media', NEW."media_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."platform" IS DISTINCT FROM OLD."platform" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'platform', NEW."platform"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."source_id" IS DISTINCT FROM OLD."source_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'source_id', NEW."source_id", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."url" IS DISTINCT FROM OLD."url" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'url', NEW."url", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."published_date" IS DISTINCT FROM OLD."published_date" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'published_date', to_char(NEW."published_date", 'YYYY-MM-DD'), false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."work_origin" IS DISTINCT FROM OLD."work_origin" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'work_origin', NEW."work_origin"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."work_status" IS DISTINCT FROM OLD."work_status" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'work_status', NEW."work_status"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."work_width" IS DISTINCT FROM OLD."work_width" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'work_width', NEW."work_width"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."work_height" IS DISTINCT FROM OLD."work_height" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'work_height', NEW."work_height"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."work_duration" IS DISTINCT FROM OLD."work_duration" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'work_duration', NEW."work_duration"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."title" IS DISTINCT FROM OLD."title" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'title', NEW."title", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."description" IS DISTINCT FROM OLD."description" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'description', NEW."description", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."thumbnail_url" IS DISTINCT FROM OLD."thumbnail_url" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'thumbnail_url', NEW."thumbnail_url", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."thumbnail_mime" IS DISTINCT FROM OLD."thumbnail_mime" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'thumbnail_mime', NEW."thumbnail_mime"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."thumbnail_hash" IS DISTINCT FROM OLD."thumbnail_hash" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'thumbnail_hash', NEW."thumbnail_hash", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."uploader_id" IS DISTINCT FROM OLD."uploader_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'uploader_id', NEW."uploader_id", false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	IF TG_OP = 'INSERT' OR NEW."added_by_id" IS DISTINCT FROM OLD."added_by_id" THEN
		rev := coalesce(rev, otodb_current_revision());
		INSERT INTO otodb_revisionchange (rev_id, target_type_id, target_id, target_column, target_value, deleted, restored)
		VALUES (rev, own_ct, tid, 'added_by', NEW."added_by_id"::text, false, false)
		ON CONFLICT (rev_id, target_type_id, target_id, target_column) DO UPDATE SET target_value = EXCLUDED.target_value
		RETURNING id INTO cid;
		PERFORM otodb_emit_entity(cid, own_ct, NEW."id", route);
		PERFORM otodb_emit_entity(cid, ct_mediawork, NEW."media_id", route);
	END IF;
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS zz_otodb_worksource_capture ON otodb_worksource;
CREATE OR REPLACE TRIGGER zz_otodb_worksource_capture_i
AFTER INSERT ON otodb_worksource
FOR EACH ROW EXECUTE FUNCTION otodb_worksource_capture();
CREATE OR REPLACE TRIGGER zz_otodb_worksource_capture_u
AFTER UPDATE ON otodb_worksource
FOR EACH ROW WHEN (OLD."media_id" IS DISTINCT FROM NEW."media_id"
	 OR OLD."platform" IS DISTINCT FROM NEW."platform"
	 OR OLD."source_id" IS DISTINCT FROM NEW."source_id"
	 OR OLD."url" IS DISTINCT FROM NEW."url"
	 OR OLD."published_date" IS DISTINCT FROM NEW."published_date"
	 OR OLD."work_origin" IS DISTINCT FROM NEW."work_origin"
	 OR OLD."work_status" IS DISTINCT FROM NEW."work_status"
	 OR OLD."work_width" IS DISTINCT FROM NEW."work_width"
	 OR OLD."work_height" IS DISTINCT FROM NEW."work_height"
	 OR OLD."work_duration" IS DISTINCT FROM NEW."work_duration"
	 OR OLD."title" IS DISTINCT FROM NEW."title"
	 OR OLD."description" IS DISTINCT FROM NEW."description"
	 OR OLD."thumbnail_url" IS DISTINCT FROM NEW."thumbnail_url"
	 OR OLD."thumbnail_mime" IS DISTINCT FROM NEW."thumbnail_mime"
	 OR OLD."thumbnail_hash" IS DISTINCT FROM NEW."thumbnail_hash"
	 OR OLD."uploader_id" IS DISTINCT FROM NEW."uploader_id"
	 OR OLD."added_by_id" IS DISTINCT FROM NEW."added_by_id")
EXECUTE FUNCTION otodb_worksource_capture();
CREATE OR REPLACE TRIGGER zz_otodb_worksource_capture_d
AFTER DELETE ON otodb_worksource
FOR EACH ROW EXECUTE FUNCTION otodb_worksource_capture();
