"""
Django settings for ___ project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = os.environ.get('OTODB_DEBUG', 'False').lower() == 'true'
DEBUG_TOOLBAR = DEBUG and os.environ.get('OTODB_DEBUG_TOOLBAR', 'True').lower() != 'false'

if not DEBUG and 'OTODB_SECRET_KEY' not in os.environ:
    print('No secret key provided (OTODB_SECRET_KEY) -- exiting')
    exit(1)

SECRET_KEY = os.environ.get('OTODB_SECRET_KEY', '1145141919')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('OTODB_ALLOWED_HOSTS', "").split(',')
    if host
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'otodb',
    'otodb.account',
    'otodb.wiki',
    'simple_history',
    'taggit',
    'rolepermissions',
]

if DEBUG_TOOLBAR:
    INSTALLED_APPS = ['debug_toolbar'] + INSTALLED_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

if DEBUG_TOOLBAR:
    MIDDLEWARE = ['debug_toolbar.middleware.DebugToolbarMiddleware'] + MIDDLEWARE

ROOT_URLCONF = '___.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'otodb.context_preprocessors.G',
            ],
        },
    },
]

WSGI_APPLICATION = '___.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_DEBUG = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}
DATABASE_PROD = {
    'ENGINE': 'django.db.backends.postgresql',
    'OPTIONS': {},
}

if not DEBUG and 'OTODB_DB_SERVICE' in os.environ and 'OTODB_DB_PASSFILE' in os.environ:
    DATABASE_PROD['OPTIONS'] = {
        'service': os.environ['OTODB_DB_SERVICE'],
        'passfile': os.environ['OTODB_DB_PASSFILE'],
    }
elif not DEBUG:
    DATABASE_PROD['NAME'] = os.environ['OTODB_DB_NAME']
    DATABASE_PROD['USER'] = os.environ['OTODB_DB_USER']
    DATABASE_PROD['PASSWORD'] = os.environ['OTODB_DB_PASSWORD']
    DATABASE_PROD['HOST'] = os.environ['OTODB_DB_HOST']
    DATABASE_PROD['PORT'] = os.environ['OTODB_DB_PORT']

DATABASES = {
    'default': DATABASE_DEBUG if DEBUG else DATABASE_PROD
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "account.Account"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('OTODB_TIME_ZONE', 'UTC')

USE_I18N = True

USE_TZ = True

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = 'static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    ip.strip()
    for ip in os.environ.get('OTODB_INTERNAL_IPS', "").split(',')
    if ip
]

TAGGIT_CASE_INSENSITIVE = True
TAGGIT_TAGS_FROM_STRING = 'otodb.common.utils.space_splitter'
TAGGIT_STRING_FROM_TAGS = 'otodb.common.utils.space_joiner'

ROLEPERMISSIONS_MODULE = '___.roles'

OTODB_CONFIG_DICT = {
    'site_name': os.environ.get(
        'OTODB_CONF_SITE_NAME',
        'otoDB'
    )
}
